// packages/docs/angular-docs/src/routes/components+/combobox+/demos/combobox-sizes-demo.ts
import {Component} from "@angular/core"

import {ComboboxModule} from "@qualcomm-ui/angular/combobox"
import {useListCollection} from "@qualcomm-ui/angular-core/collection"
import type {ComboboxInputValueChangeDetails} from "@qualcomm-ui/core/combobox"

const cityList = ["San Diego", "Dallas", "Denver"]

@Component({
  imports: [ComboboxModule],
  selector: "combobox-sizes-demo",
  template: `
    <div class="flex flex-col items-center gap-4">
      <q-combobox
        aria-label="City"
        class="w-40"
        placeholder="sm"
        size="sm"
        [collection]="listCollection.collection()"
        (inputValueChanged)="onInputChange($event)"
      />
      <q-combobox
        aria-label="City"
        class="w-48"
        placeholder="md"
        size="md"
        [collection]="listCollection.collection()"
        (inputValueChanged)="onInputChange($event)"
      />
      <q-combobox
        aria-label="City"
        class="w-56"
        placeholder="lg"
        size="lg"
        [collection]="listCollection.collection()"
        (inputValueChanged)="onInputChange($event)"
      />
    </div>
  `,
})
export class ComboboxSizesDemo {
  readonly listCollection = useListCollection<string>({
    filter: "contains",
    items: cityList,
  })

  onInputChange(event: ComboboxInputValueChangeDetails) {
    this.listCollection.filterText.set(event.inputValue)
  }
}

// packages/docs/react-docs/src/routes/components+/combobox+/demos/combobox-sizes-demo.tsx
import type {ComboboxInputValueChangeDetails} from "@qualcomm-ui/core/combobox"
import {Combobox} from "@qualcomm-ui/react/combobox"
import {useListCollection} from "@qualcomm-ui/react-core/collection"
import {useFilter} from "@qualcomm-ui/react-core/locale"

const cityList = ["San Diego", "Dallas", "Denver"]

export function ComboboxSizesDemo() {
  const {contains} = useFilter({sensitivity: "base"})

  const {collection, filter} = useListCollection({
    filter: contains,
    initialItems: cityList,
  })

  function handleInputChange(details: ComboboxInputValueChangeDetails) {
    filter(details.inputValue)
  }

  return (
    <div className="flex flex-col items-center gap-4">
      <Combobox
        aria-label="City"
        className="w-40"
        collection={collection}
        onInputValueChange={handleInputChange}
        placeholder="sm"
        positioning={{sameWidth: true}}
        size="sm"
      />
      <Combobox
        aria-label="City"
        className="w-48"
        collection={collection}
        onInputValueChange={handleInputChange}
        placeholder="md"
        positioning={{sameWidth: true}}
        size="md"
      />
      <Combobox
        aria-label="City"
        className="w-56"
        collection={collection}
        onInputValueChange={handleInputChange}
        placeholder="lg"
        positioning={{sameWidth: true}}
        size="lg"
      />
    </div>
  )
}
