// packages/docs/angular-docs/src/routes/components+/combobox+/demos/combobox-explorer-demo.ts
import {Component} from "@angular/core"

import {ComboboxModule} from "@qualcomm-ui/angular/combobox"
import {useListCollection} from "@qualcomm-ui/angular-core/collection"

@Component({
  imports: [ComboboxModule],
  selector: "combobox-explorer-demo",
  template: `
    <q-combobox
      class="w-48"
      defaultOpen
      disablePortal
      hint="Choose a framework"
      label="Framework"
      placeholder="Select a framework"
      [collection]="listCollection.collection()"
      [defaultValue]="['React']"
    />
  `,
})
export class ComboboxExplorerDemo {
  readonly listCollection = useListCollection<string>({
    filter: "contains",
    items: ["React", "Angular", "Vue"],
  })
}

// packages/docs/react-docs/src/routes/components+/combobox+/demos/combobox-explorer-demo.tsx
import type {ReactElement} from "react"

import {Combobox} from "@qualcomm-ui/react/combobox"
import {useListCollection} from "@qualcomm-ui/react-core/collection"

export function ComboboxExplorerDemo(): ReactElement {
  const {collection} = useListCollection({
    initialItems: ["React", "Angular", "Vue"],
  })

  return (
    <Combobox
      className="w-48"
      collection={collection}
      defaultOpen
      defaultValue={["React"]}
      hint="Choose a framework"
      label="Framework"
      placeholder="Select a framework"
      portalProps={{disabled: true}}
    />
  )
}
