// packages/frameworks/react/src/text-area/text-area.tsx
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {ReactElement, ReactNode} from "react"

import {useOptionalContentId} from "@qualcomm-ui/react-core/machine"
import {useControlledId} from "@qualcomm-ui/react-core/state"

import {TextAreaCounter, type TextAreaCounterProps} from "./text-area-counter"
import {
  TextAreaErrorText,
  type TextAreaErrorTextProps,
} from "./text-area-error-text"
import {TextAreaHint, type TextAreaHintProps} from "./text-area-hint"
import {TextAreaInput, type TextAreaInputProps} from "./text-area-input"
import {TextAreaLabel, type TextAreaLabelProps} from "./text-area-label"
import {TextAreaRoot, type TextAreaRootProps} from "./text-area-root"

export interface TextAreaProps extends TextAreaRootProps {
  /**
   * The simple TextArea doesn't support children.
   */
  children?: never

  /**
   * Controls whether to display the counter element.
   *
   * - `true`: always show the counter
   * - `false`: never show the counter
   * - `undefined` (default): only show the counter if `maxLength` is set
   */
  counter?: boolean

  /**
   * Props applied to the counter element.
   */
  counterProps?: TextAreaCounterProps

  /**
   * Optional error that describes the element when {@link invalid} is true.
   */
  errorText?: string

  /**
   * Props applied to the error text element.
   */
  errorTextProps?: TextAreaErrorTextProps

  /**
   * Optional hint describing the element. This element is automatically
   * associated with the component's textarea element for accessibility.
   */
  hint?: ReactNode

  /**
   * Props applied to the hint element.
   */
  hintProps?: TextAreaHintProps

  /**
   * Props applied to the textarea element.
   */
  inputProps?: TextAreaInputProps

  /**
   * Optional label describing the element. Recommended. This element is
   * automatically associated with the component's input element for
   * accessibility.
   */
  label?: ReactNode

  /**
   * Props applied to the label element.
   */
  labelProps?: TextAreaLabelProps

  /**
   * HTML {@link https://www.w3schools.com/tags/att_input_maxlength.asp maxlength} attribute,
   * passed to the underlying textarea element.
   */
  maxLength?: number

  /**
   * HTML {@link https://www.w3schools.com/tags/att_input_placeholder.asp placeholder} attribute,
   * passed to the underlying textarea element.
   */
  placeholder?: string
}

export function TextArea({
  counter,
  counterProps,
  errorText,
  errorTextProps,
  hint,
  hintProps,
  inputProps,
  label,
  labelProps,
  maxLength,
  placeholder,
  ...props
}: TextAreaProps): ReactElement {
  const labelContent = label || labelProps?.children
  const errorTextContent = errorText || errorTextProps?.children
  const hintContent = hint || hintProps?.children

  const ids = {
    counter: useControlledId(counterProps?.id),
    errorText: useOptionalContentId(errorTextContent, errorTextProps),
    hint: useOptionalContentId(hintContent, hintProps),
    input: useControlledId(inputProps?.id),
    label: useOptionalContentId(labelContent, labelProps),
    ...props.ids,
  }

  return (
    <TextAreaRoot {...props} ids={ids} maxLength={maxLength}>
      {labelContent ? (
        <TextAreaLabel {...labelProps} id={ids.label}>
          {labelContent}
        </TextAreaLabel>
      ) : null}

      {(counter ?? maxLength !== undefined) ? (
        <TextAreaCounter {...counterProps} />
      ) : null}

      <TextAreaInput
        maxLength={maxLength}
        placeholder={placeholder}
        {...inputProps}
        id={ids.input}
      />

      {hintContent ? (
        <TextAreaHint {...hintProps} id={ids.hint}>
          {hintContent}
        </TextAreaHint>
      ) : null}

      {errorTextContent ? (
        <TextAreaErrorText {...errorTextProps} id={ids.errorText}>
          {errorTextContent}
        </TextAreaErrorText>
      ) : null}
    </TextAreaRoot>
  )
}

// packages/frameworks/angular/src/text-area/text-area.component.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {booleanAttribute, Component, input} from "@angular/core"

import {provideTextAreaContext} from "@qualcomm-ui/angular-core/text-area"
import type {Booleanish} from "@qualcomm-ui/utils/coercion"

import {provideQdsTextAreaContext} from "./qds-text-area-context.service"
import {TextAreaRootDirective} from "./text-area-root.directive"

@Component({
  providers: [provideTextAreaContext(), provideQdsTextAreaContext()],
  selector: "q-text-area:not([q-text-area-root])",
  standalone: false,
  template: `
    <ng-content select="[q-text-area-label]">
      @if (label()) {
        <label q-text-area-label>{{ label() }}</label>
      }
    </ng-content>

    <ng-content select="[q-text-area-counter]">
      @if (counter() ?? maxLength() !== undefined) {
        <div q-text-area-counter></div>
      }
    </ng-content>

    <textarea
      q-text-area-input
      [maxLength]="maxLength()"
      [placeholder]="placeholder()"
    ></textarea>

    <ng-content select="[q-text-area-hint]">
      @if (hint()) {
        <span q-text-area-hint>
          {{ hint() }}
        </span>
      }
    </ng-content>

    <ng-content select="[q-text-area-error-text]">
      @if (errorText()) {
        <div q-text-area-error-text>
          {{ errorText() }}
        </div>
      }
    </ng-content>
  `,
})
export class TextAreaComponent extends TextAreaRootDirective {
  /**
   * Controls whether to display the counter element.
   *
   * - `true`: always show the counter
   * - `false`: never show the counter
   * - `undefined` (default): only show the counter if `maxLength` is set
   */
  readonly counter = input<boolean | undefined, Booleanish>(undefined, {
    transform: booleanAttribute,
  })

  /**
   * Optional error that describes the element when {@link invalid} is true.
   *
   * @remarks
   * To customize the element, provide it using the directive instead:
   *
   * ```angular-html
   * <div q-text-area-error-text>...</div>
   * ```
   */
  readonly errorText = input<string | undefined | null>()

  /**
   * Optional hint describing the element. This element is automatically
   * associated with the component's input element for accessibility.
   *
   * @remarks
   * To customize the element, provide it using the directive instead:
   *
   * ```angular-html
   * <div q-text-area-hint>...</div>
   * ```
   */
  readonly hint = input<string | undefined | null>()

  /**
   * Optional label describing the element. Recommended. This element is
   * automatically associated with the component's input element for
   * accessibility.
   *
   * @remarks
   * To customize the element, provide it using the directive instead:
   *
   * ```angular-html
   * <label q-text-area-label>...</label>
   * ```
   */
  readonly label = input<string | undefined>()

  /**
   * HTML {@link https://www.w3schools.com/tags/att_input_placeholder.asp placeholder} attribute,
   * passed to the internal input element.
   */
  readonly placeholder = input<string>("")
}
