// packages/docs/react-docs/src/routes/components+/link+/demos/link-colors-demo.tsx
import type {ReactElement} from "react"

import {Link} from "@qualcomm-ui/react/link"

export function LinkColorsDemo(): ReactElement {
  return (
    <div className="flex flex-col gap-4">
      {/* preview */}
      <Link>default</Link>
      <Link emphasis="neutral">neutral</Link>
      <Link emphasis="brand">brand</Link>
      <div className="bg-persistent-black p-4">
        <Link emphasis="white-persistent">white-persistent</Link>
      </div>
      {/* preview */}
    </div>
  )
}

// packages/docs/angular-docs/src/routes/components+/link+/demos/link-colors-demo.ts
import {Component} from "@angular/core"

import {LinkDirective} from "@qualcomm-ui/angular/link"

@Component({
  imports: [LinkDirective],
  selector: "link-colors-demo",
  template: `
    <div class="flex flex-col gap-4">
      <!-- preview -->
      <a q-link>default</a>
      <a emphasis="neutral" q-link>neutral</a>
      <a emphasis="brand" q-link>brand</a>
      <div class="bg-persistent-black p-4">
        <a emphasis="white-persistent" q-link>white-persistent</a>
      </div>
      <!-- preview -->
    </div>
  `,
})
export class LinkColorsDemo {}
