// packages/frameworks/react/src/number-input/number-input-unit-select.tsx
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {type ReactElement, useCallback, useMemo, useState} from "react"

import {ChevronDown, ChevronUp} from "lucide-react"

import type {UnitOption} from "@qualcomm-ui/qds-core/number-input"
import {Icon} from "@qualcomm-ui/react/icon"
import {Menu} from "@qualcomm-ui/react/menu"
import {useMenuContext} from "@qualcomm-ui/react-core/menu"
import {useNumberInputContext} from "@qualcomm-ui/react-core/number-input"
import {Portal} from "@qualcomm-ui/react-core/portal"
import type {IdProp} from "@qualcomm-ui/react-core/system"
import {mergeProps} from "@qualcomm-ui/utils/merge-props"

import {useQdsNumberInputContext} from "./qds-number-input-context"

export type {UnitOption}

export interface NumberInputUnitSelectProps extends IdProp {
  /**
   * The initial selected unit. Defaults to the first option if not provided.
   */
  defaultUnit?: string

  /**
   * Callback fired when the selected unit changes.
   */
  onUnitChange?: (value: string) => void

  /**
   * Array of unit options to display in the dropdown.
   */
  options: UnitOption[]
}

function NumberInputUnitSelectTriggerContent(): ReactElement {
  const menuContext = useMenuContext()

  return (
    <Icon
      data-part="chevron"
      icon={menuContext.open ? ChevronUp : ChevronDown}
      size="sm"
    />
  )
}

export function NumberInputUnitSelect({
  defaultUnit,
  id,
  onUnitChange,
  options,
}: NumberInputUnitSelectProps): ReactElement {
  const numberInputContext = useNumberInputContext()
  const qdsNumberInputContext = useQdsNumberInputContext()

  const [selectedValue, setSelectedValue] = useState(
    () => defaultUnit ?? options[0]?.value ?? "",
  )

  const effectiveSelectedValue = useMemo(() => {
    const isValidSelection = options.some((opt) => opt.value === selectedValue)
    if (isValidSelection) {
      return selectedValue
    }

    return options.some((opt) => opt.value === defaultUnit)
      ? defaultUnit!
      : (options[0]?.value ?? "")
  }, [options, defaultUnit, selectedValue])

  const handleValueChange = useCallback(
    (newValue: string) => {
      setSelectedValue(newValue)
      onUnitChange?.(newValue)
    },
    [onUnitChange],
  )

  const menuSize =
    qdsNumberInputContext.size === "lg" ? "md" : qdsNumberInputContext.size
  const selectedOption = options.find(
    (opt) => opt.value === effectiveSelectedValue,
  )
  const displayLabel = selectedOption?.label ?? ""

  const buttonBindings = mergeProps(
    numberInputContext.getUnitSelectBindings(),
    qdsNumberInputContext.getUnitSelectBindings(),
  )

  return (
    <Menu.Root size={menuSize}>
      <Menu.Trigger>
        <button id={id} {...buttonBindings}>
          <span>{displayLabel}</span>
          <NumberInputUnitSelectTriggerContent />
        </button>
      </Menu.Trigger>
      <Portal>
        <Menu.Positioner>
          <Menu.Content>
            <Menu.RadioItemGroup
              onValueChange={handleValueChange}
              value={effectiveSelectedValue}
            >
              {options.map((option) => (
                <Menu.RadioItem key={option.value} value={option.value}>
                  <Menu.ItemLabel>
                    {option.displayText ?? option.label}
                  </Menu.ItemLabel>
                  <Menu.ItemIndicator />
                </Menu.RadioItem>
              ))}
            </Menu.RadioItemGroup>
          </Menu.Content>
        </Menu.Positioner>
      </Portal>
    </Menu.Root>
  )
}

// packages/frameworks/angular/src/number-input/number-input-unit-select.component.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {
  Component,
  computed,
  effect,
  inject,
  input,
  type OnInit,
  output,
  signal,
  type Signal,
  untracked,
} from "@angular/core"
import {ChevronDown, ChevronUp} from "lucide-angular"

import {
  provideQdsMenuContext,
  QdsMenuContextService,
} from "@qualcomm-ui/angular/menu"
import {provideIcons} from "@qualcomm-ui/angular-core/lucide"
import {normalizeProps} from "@qualcomm-ui/angular-core/machine"
import {
  CoreMenuRootDirective,
  provideMenuContext,
  provideMenuMachineContext,
  provideMenuTriggerContext,
  useMenuContext,
} from "@qualcomm-ui/angular-core/menu"
import {useNumberInputContext} from "@qualcomm-ui/angular-core/number-input"
import {providePresenceContext} from "@qualcomm-ui/angular-core/presence"
import {createQdsMenuApi} from "@qualcomm-ui/qds-core/menu"
import type {UnitOption} from "@qualcomm-ui/qds-core/number-input"

import {useQdsNumberInputContext} from "./qds-number-input-context.service"

export type {UnitOption}

@Component({
  providers: [
    provideMenuContext(),
    provideMenuTriggerContext(),
    provideMenuMachineContext(),
    providePresenceContext(),
    provideQdsMenuContext(),
    provideIcons({ChevronDown, ChevronUp}),
  ],
  selector: "q-number-input-unit-select",
  standalone: false,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
  template: `
    <button q-menu-trigger [q-bind]="unitSelectBindings()">
      <span>{{ selectedLabel() }}</span>
      <svg
        data-part="chevron"
        size="sm"
        [qIcon]="menuContext().open ? 'ChevronUp' : 'ChevronDown'"
      ></svg>
    </button>
    <ng-template qPortal>
      <div q-menu-positioner>
        <div q-menu-content>
          <div
            q-menu-radio-item-group
            [value]="selectedValue()"
            (valueChange)="onUnitChange($event)"
          >
            @for (option of options(); track option.value) {
              <button q-menu-radio-item [value]="option.value">
                <span q-menu-item-label>
                  {{ option.displayText ?? option.label }}
                </span>
                <span q-menu-item-indicator></span>
              </button>
            }
          </div>
        </div>
      </div>
    </ng-template>
  `,
})
export class NumberInputUnitSelectComponent
  extends CoreMenuRootDirective
  implements OnInit
{
  /**
   * The initial selected unit. Defaults to the first option if not provided.
   */
  readonly defaultUnit = input<string>()

  /**
   * Array of unit options to display in the dropdown.
   */
  readonly options = input.required<UnitOption[]>()

  /**
   * Emits when the selected unit changes.
   */
  readonly unitChange = output<string>()

  /**
   * The currently selected value (internal state).
   */
  protected readonly selectedValue = signal<string>("")

  protected readonly numberInputContext = useNumberInputContext()
  protected readonly qdsNumberInputContext = useQdsNumberInputContext()
  protected readonly qdsMenuService = inject(QdsMenuContextService)
  protected readonly menuContext = useMenuContext()

  protected readonly unitSelectBindings = computed(() => ({
    ...this.numberInputContext().getUnitSelectBindings(),
    ...this.qdsNumberInputContext().getUnitSelectBindings(),
  }))

  constructor() {
    super()

    effect(() => {
      const opts = this.options()
      const defaultVal = this.defaultUnit()

      untracked(() => {
        const currentValue = this.selectedValue()
        const isValidSelection =
          currentValue !== "" && opts.some((opt) => opt.value === currentValue)

        if (isValidSelection) {
          return
        }

        const nextValue = opts.some((opt) => opt.value === defaultVal)
          ? defaultVal
          : (opts[0]?.value ?? "")

        if (nextValue !== currentValue) {
          this.selectedValue.set(nextValue ?? "")
        }
      })
    })
  }

  protected readonly selectedLabel: Signal<string> = computed(() => {
    const currentValue = this.selectedValue()
    const opts = this.options()
    const selected = opts.find((opt) => opt.value === currentValue)
    return selected?.label ?? ""
  })

  protected onUnitChange(value: string | undefined): void {
    if (value) {
      this.selectedValue.set(value)
      this.unitChange.emit(value)
    }
  }

  override ngOnInit() {
    super.ngOnInit()

    const qdsMenuApi = computed(() => {
      const inputSize = this.qdsNumberInputContext().size
      const menuSize = inputSize === "lg" ? "md" : inputSize
      return createQdsMenuApi({size: menuSize}, normalizeProps)
    })

    this.qdsMenuService.init(qdsMenuApi)
  }
}
