// packages/frameworks/angular/src/select/select.component.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {
  booleanAttribute,
  ChangeDetectionStrategy,
  Component,
  input,
} from "@angular/core"

import {provideQdsInputContext} from "@qualcomm-ui/angular/input"
import {provideSelectContext} from "@qualcomm-ui/angular-core/select"
import type {Booleanish} from "@qualcomm-ui/utils/coercion"

import {
  provideQdsSelectContext,
  useQdsSelectContext,
} from "./qds-select-context.service"
import {SelectRootDirective} from "./select-root.directive"

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "[attr.aria-label]": "undefined",
    "[attr.aria-labelledby]": "undefined",
  },
  providers: [
    provideSelectContext(),
    provideQdsSelectContext(),
    provideQdsInputContext(),
  ],
  selector: "q-select",
  standalone: false,
  template: `
    <ng-content select="[q-select-label]">
      @if (label()) {
        <div q-select-label>{{ label() }}</div>
      }
    </ng-content>

    <ng-content select="[q-select-control]">
      <div
        q-select-control
        [aria-label]="ariaLabel()"
        [aria-labelledby]="ariaLabelledby()"
      >
        <ng-content select="[q-select-value-text]">
          <span q-select-value-text></span>
        </ng-content>
        <ng-content select="[q-select-clear-trigger]">
          @if (clearable()) {
            <button q-select-clear-trigger></button>
          }
        </ng-content>
        <ng-content select="[q-select-indicator]">
          <button q-select-indicator></button>
        </ng-content>
        <ng-content select="[q-select-error-indicator]">
          <div q-select-error-indicator></div>
        </ng-content>
      </div>
    </ng-content>

    <ng-content select="[q-select-hint]">
      @if (hint()) {
        <div q-select-hint>{{ hint() }}</div>
      }
    </ng-content>

    <ng-content select="[q-select-error-text]">
      @if (errorText()) {
        <div q-select-error-text>{{ errorText() }}</div>
      }
    </ng-content>

    <ng-content select="q-select-hidden-select">
      <select q-select-hidden-select></select>
    </ng-content>

    <ng-template qPortal [disabled]="disablePortal()">
      <div q-select-positioner>
        <ng-content select="[q-select-content]">
          <div q-select-content>
            @for (
              item of collection().items;
              track collection().getItemValue(item)
            ) {
              <div q-select-item [item]="item">
                @if (
                  selectContext.context().multiple &&
                  qdsSelectContext().selectionIndicator === "checkbox"
                ) {
                  <span q-select-item-checkbox></span>
                }
                <span q-select-item-text>
                  {{ collection().stringifyItem(item) }}
                </span>
                @if (
                  !selectContext.context().multiple ||
                  qdsSelectContext().selectionIndicator !== "checkbox"
                ) {
                  <span q-select-item-indicator></span>
                }
              </div>
            }
          </div>
        </ng-content>
      </div>
    </ng-template>
  `,
})
export class SelectComponent extends SelectRootDirective {
  protected readonly qdsSelectContext = useQdsSelectContext()

  /**
   * ARIA label applied to the control element. Use this if you omit the {@link
   * label}
   *
   * @since 2.9.0
   */
  readonly ariaLabel = input<string | undefined>(undefined, {
    alias: "aria-label",
  })

  /**
   * ID reference for an external label applied to the control element.
   *
   * @since 2.9.0
   */
  readonly ariaLabelledby = input<string | undefined>(undefined, {
    alias: "aria-labelledby",
  })

  /**
   * When `true`, renders a clear button that resets the input value on click.
   * The button only appears when the input has a value.
   *
   * @default true
   */
  readonly clearable = input<boolean | undefined, Booleanish>(true, {
    transform: booleanAttribute,
  })

  /**
   * Set to true to disable portalling behavior for the select dropdown content.
   */
  readonly disablePortal = input<boolean | undefined, Booleanish>(undefined, {
    transform: booleanAttribute,
  })

  /**
   * Optional error that describes the element when {@link invalid} is true.
   *
   * @remarks
   * To customize the element, provide it using the directive instead:
   *
   * ```angular-html
   * <div q-select-error-text>...</div>
   * ```
   */
  readonly errorText = input<string | undefined | null>()

  /**
   * Optional hint describing the element. This element is automatically
   * associated with the component's input element for accessibility.
   *
   * @remarks
   * To customize the element, provide it using the directive instead:
   *
   * ```angular-html
   * <div q-select-hint>...</div>
   * ```
   */
  readonly hint = input<string | undefined | null>()

  /**
   * Optional label describing the element. Recommended. This element is
   * automatically associated with the component's input element for
   * accessibility.
   *
   * @remarks
   * To customize the element, provide it using the directive instead:
   *
   * ```angular-html
   * <div q-select-label>...</div>
   * ```
   */
  readonly label = input<string | undefined>()
}

// packages/frameworks/react/src/select/select.tsx
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {ReactElement, ReactNode} from "react"

import {useOptionalContentId} from "@qualcomm-ui/react-core/machine"
import {Portal, type PortalProps} from "@qualcomm-ui/react-core/portal"
import {useControlledId} from "@qualcomm-ui/react-core/state"

import {
  SelectClearTrigger,
  type SelectClearTriggerProps,
} from "./select-clear-trigger"
import {SelectContent, type SelectContentProps} from "./select-content"
import {SelectControl, type SelectControlProps} from "./select-control"
import {
  SelectErrorIndicator,
  type SelectErrorIndicatorProps,
} from "./select-error-indicator"
import {SelectErrorText, type SelectErrorTextProps} from "./select-error-text"
import {
  SelectHiddenSelect,
  type SelectHiddenSelectProps,
} from "./select-hidden-select"
import {SelectHint, type SelectHintProps} from "./select-hint"
import {SelectIndicator, type SelectIndicatorProps} from "./select-indicator"
import {SelectItems} from "./select-items"
import {SelectLabel, type SelectLabelProps} from "./select-label"
import {SelectPositioner, type SelectPositionerProps} from "./select-positioner"
import {SelectRoot, type SelectRootProps} from "./select-root"
import {SelectValueText, type SelectValueTextProps} from "./select-value-text"

export interface SelectProps extends SelectRootProps {
  /**
   * {@link https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-label aria-label}
   * attribute, forwarded to the hidden select element.
   */
  "aria-label"?: string | undefined

  /**
   * {@link https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-labelledby aria-labelledby}
   * attribute, forwarded to the hidden select element. If you provide a {@link
   * label}, omit this prop.
   */
  "aria-labelledby"?: string | undefined

  /**
   * When `true`, renders a clear button that resets the input value on click.
   * The button only appears when the input has a value.
   *
   * @default true
   */
  clearable?: boolean

  /**
   * Props applied to the clear trigger element.
   *
   * @inheritDoc
   */
  clearTriggerProps?: SelectClearTriggerProps

  /**
   * Props applied to the content element.
   *
   * @inheritDoc
   */
  contentProps?: SelectContentProps

  /**
   * Props applied to the trigger element.
   *
   * @inheritDoc
   */
  controlProps?: SelectControlProps

  /**
   * Props applied to the error indicator element.
   *
   * @inheritDoc
   */
  errorIndicatorProps?: SelectErrorIndicatorProps

  /**
   * Optional error that describes the element when {@link invalid} is true.
   */
  errorText?: ReactNode

  /**
   * Props applied to the error text element.
   *
   * @inheritDoc
   */
  errorTextProps?: SelectErrorTextProps

  /**
   * Optional hint describing the element. This element is automatically
   * associated with the component's input element for accessibility.
   */
  hint?: ReactNode

  /**
   * Props applied to the label element.
   *
   * @inheritDoc
   */
  hintProps?: SelectHintProps

  /**
   * Props applied to the indicator element.
   *
   * @inheritDoc
   */
  indicatorProps?: SelectIndicatorProps

  /**
   * Optional label describing the element. Recommended. This element is
   * automatically associated with the component's input element for
   * accessibility.
   */
  label?: ReactNode

  /**
   * Props applied to the label element.
   *
   * @inheritDoc
   */
  labelProps?: SelectLabelProps

  /**
   * Props applied to the portal element.
   *
   * @inheritDoc
   */
  portalProps?: PortalProps

  /**
   * Props applied to the positioner element.
   *
   * @inheritDoc
   */
  positionerProps?: SelectPositionerProps

  /**
   * Props applied to the select element.
   *
   * @inheritDoc
   */
  selectProps?: SelectHiddenSelectProps

  /**
   * Props applied to the value text element.
   *
   * @inheritDoc
   */
  valueTextProps?: SelectValueTextProps
}

export function Select({
  "aria-label": ariaLabel,
  "aria-labelledby": ariaLabelledBy,
  clearable = true,
  clearTriggerProps,
  contentProps,
  controlProps,
  errorIndicatorProps,
  errorText,
  errorTextProps,
  hint,
  hintProps,
  indicatorProps,
  label,
  labelProps,
  portalProps,
  positionerProps,
  selectProps,
  valueTextProps,
  ...props
}: SelectProps): ReactElement {
  const labelContent = label || labelProps?.children
  const hintContent = hint || hintProps?.children
  const errorTextContent = errorText || errorTextProps?.children

  const ids = {
    clearTrigger: useOptionalContentId(clearable, clearTriggerProps),
    content: useControlledId(contentProps?.id),
    control: useControlledId(controlProps?.id),
    errorText: useOptionalContentId(errorTextContent, errorTextProps),
    hiddenSelect: useControlledId(selectProps?.id),
    hint: useOptionalContentId(hintContent, hintProps),
    label: useOptionalContentId(labelContent, labelProps),
    positioner: useControlledId(positionerProps?.id),
    root: useControlledId(props.id),
    ...props.ids,
  }

  return (
    <SelectRoot {...props} id={ids.root} ids={ids}>
      <SelectLabel {...labelProps} id={ids.label}>
        {labelContent}
      </SelectLabel>
      <SelectControl {...controlProps} id={ids.control}>
        <SelectValueText {...valueTextProps} />
        {clearable ? (
          <SelectClearTrigger {...clearTriggerProps} id={ids.clearTrigger} />
        ) : null}
        <SelectErrorIndicator {...errorIndicatorProps} />
        <SelectIndicator {...indicatorProps} />
      </SelectControl>

      {hintContent ? (
        <SelectHint {...hintProps} id={ids.hint}>
          {hintContent}
        </SelectHint>
      ) : null}

      {errorTextContent ? (
        <SelectErrorText {...errorTextProps} id={ids.errorText}>
          {errorTextContent}
        </SelectErrorText>
      ) : null}

      <SelectHiddenSelect
        aria-label={ariaLabel}
        aria-labelledby={ariaLabelledBy}
        {...selectProps}
        id={ids.hiddenSelect}
      />

      <Portal {...portalProps}>
        <SelectPositioner {...positionerProps} id={ids.positioner}>
          <SelectContent {...contentProps} id={ids.content}>
            <SelectItems />
          </SelectContent>
        </SelectPositioner>
      </Portal>
    </SelectRoot>
  )
}
