// packages/frameworks/react/src/password-input/password-input.tsx
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {ReactElement, ReactNode} from "react"

import {useOptionalContentId} from "@qualcomm-ui/react-core/machine"
import {useControlledId} from "@qualcomm-ui/react-core/state"

import {PasswordInputClearTrigger} from "./password-input-clear-trigger"
import {
  PasswordInputErrorIndicator,
  type PasswordInputErrorIndicatorProps,
} from "./password-input-error-indicator"
import {
  PasswordInputErrorText,
  type PasswordInputErrorTextProps,
} from "./password-input-error-text"
import {
  PasswordInputHint,
  type PasswordInputHintProps,
} from "./password-input-hint"
import {
  PasswordInputInput,
  type PasswordInputInputProps,
} from "./password-input-input"
import {
  PasswordInputInputGroup,
  type PasswordInputInputGroupProps,
} from "./password-input-input-group"
import {
  PasswordInputLabel,
  type PasswordInputLabelProps,
} from "./password-input-label"
import {
  PasswordInputRoot,
  type PasswordInputRootProps,
} from "./password-input-root"
import {
  PasswordInputVisibilityTrigger,
  type PasswordInputVisibilityTriggerProps,
} from "./password-input-visibility-trigger"

export interface PasswordInputProps extends PasswordInputRootProps {
  /**
   * {@link https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-label aria-label}
   * attribute, forwarded to the input element.
   */
  "aria-label"?: string | undefined

  /**
   * {@link https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-labelledby aria-labelledby}
   * attribute, forwarded to the input element. If you provide a {@link label},
   * omit this prop.
   */
  "aria-labelledby"?: string | undefined

  /**
   * The simple PasswordInput doesn't support children.
   */
  children?: never

  /**
   * When `true`, renders a clear button that resets the input value on click.
   * The button only appears when the input has a value.
   *
   * @default false
   */
  clearable?: boolean

  /**
   * Props applied to the error indicator element.
   *
   * @inheritDoc
   */
  errorIndicatorProps?: PasswordInputErrorIndicatorProps

  /**
   * Optional error that describes the element when {@link invalid} is true.
   */
  errorText?: string

  /**
   * Props applied to the error text element.
   *
   * @inheritDoc
   */
  errorTextProps?: PasswordInputErrorTextProps

  /**
   * Optional hint describing the element. This element is automatically
   * associated with the component's input element for accessibility.
   */
  hint?: ReactNode

  /**
   * Props applied to the label element.
   *
   * @inheritDoc
   */
  hintProps?: PasswordInputHintProps

  /**
   * Props applied to the input group element.
   *
   * @inheritDoc
   */
  inputGroupProps?: PasswordInputInputGroupProps

  /**
   * Props applied to the input element.
   *
   * @inheritDoc
   */
  inputProps?: PasswordInputInputProps

  /**
   * Optional label describing the element. Recommended. This element is
   * automatically associated with the component's input element for
   * accessibility.
   */
  label?: ReactNode

  /**
   * Props applied to the label element.
   *
   * @inheritDoc
   */
  labelProps?: PasswordInputLabelProps

  /**
   * HTML {@link https://www.w3schools.com/tags/att_input_placeholder.asp placeholder} attribute,
   * passed to the underlying input element.
   */
  placeholder?: string

  /**
   * Props applied to the visibility trigger element.
   *
   * @inheritDoc
   */
  visibilityTriggerProps?: PasswordInputVisibilityTriggerProps
}

export function PasswordInput({
  "aria-label": ariaLabel,
  "aria-labelledby": ariaLabelledBy,
  clearable,
  errorIndicatorProps,
  errorText,
  errorTextProps,
  hint,
  hintProps,
  inputGroupProps,
  inputProps,
  label,
  labelProps,
  placeholder,
  visibilityTriggerProps,
  ...props
}: PasswordInputProps): ReactElement {
  const labelContent = label || labelProps?.children
  const errorTextContent = errorText || errorTextProps?.children
  const hintContent = hint || hintProps?.children

  const visibilityTriggerId = useControlledId(visibilityTriggerProps?.id)

  const ids = {
    errorText: useOptionalContentId(errorTextContent, errorTextProps),
    hint: useOptionalContentId(hintContent, hintProps),
    input: useControlledId(inputProps?.id),
    label: useOptionalContentId(labelContent, labelProps),
    visibilityTrigger: visibilityTriggerId,
    ...props.ids,
  }

  return (
    <PasswordInputRoot {...props} ids={ids}>
      {labelContent ? (
        <PasswordInputLabel {...labelProps} id={ids.label}>
          {labelContent}
        </PasswordInputLabel>
      ) : null}

      <PasswordInputInputGroup {...inputGroupProps}>
        <PasswordInputInput
          aria-label={ariaLabel}
          aria-labelledby={ariaLabelledBy}
          placeholder={placeholder}
          {...inputProps}
          id={ids.input}
        />
        {clearable ? <PasswordInputClearTrigger /> : null}
        <PasswordInputVisibilityTrigger
          {...visibilityTriggerProps}
          id={ids.visibilityTrigger}
        />
        <PasswordInputErrorIndicator {...errorIndicatorProps} />
      </PasswordInputInputGroup>

      {hintContent ? (
        <PasswordInputHint {...hintProps} id={ids.hint}>
          {hintContent}
        </PasswordInputHint>
      ) : null}

      {errorTextContent ? (
        <PasswordInputErrorText {...errorTextProps} id={ids.errorText}>
          {errorTextContent}
        </PasswordInputErrorText>
      ) : null}
    </PasswordInputRoot>
  )
}

// packages/frameworks/angular/src/password-input/password-input.component.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {
  booleanAttribute,
  Component,
  computed,
  inject,
  input,
} from "@angular/core"

import {provideQdsInputContext} from "@qualcomm-ui/angular/input"
import {INPUT_FORM_CONTROL_CONTEXT} from "@qualcomm-ui/angular-core/input"
import type {LucideIconOrString} from "@qualcomm-ui/angular-core/lucide"
import {providePasswordInputContext} from "@qualcomm-ui/angular-core/password-input"
import type {Booleanish} from "@qualcomm-ui/utils/coercion"

import {PasswordInputRootDirective} from "./password-input-root.directive"

@Component({
  host: {
    "[attr.aria-label]": "undefined",
    "[attr.aria-labelledby]": "undefined",
  },
  providers: [
    provideQdsInputContext(),
    providePasswordInputContext(),
    {
      provide: INPUT_FORM_CONTROL_CONTEXT,
      useFactory: () => {
        const passwordInputComponent = inject(PasswordInputComponent, {
          self: true,
        })
        return passwordInputComponent.formControlContext
      },
    },
  ],
  selector: "q-password-input",
  standalone: false,
  template: `
    <ng-content select="[q-password-input-label]">
      @if (label()) {
        <label q-password-input-label>{{ label() }}</label>
      }
    </ng-content>
    <div q-password-input-input-group>
      <input
        q-password-input-input
        [aria-label]="ariaLabel()"
        [aria-labelledby]="ariaLabelledby()"
        [placeholder]="placeholder()"
      />

      <ng-content select="[q-password-input-clear-trigger]">
        @if (clearable()) {
          <button q-password-input-clear-trigger></button>
        }
      </ng-content>

      <ng-content select="[q-password-input-visibility-trigger]">
        <button q-password-input-visibility-trigger></button>
      </ng-content>

      <ng-content select="[q-password-input-error-indicator]">
        <span q-password-input-error-indicator></span>
      </ng-content>
    </div>
    <ng-content select="[q-password-input-hint]">
      @if (hint()) {
        <span q-password-input-hint>
          {{ hint() }}
        </span>
      }
    </ng-content>

    <ng-content select="[q-password-input-error-text]">
      @if (computedErrorText()) {
        <div q-password-input-error-text>
          {{ computedErrorText() }}
        </div>
      }
    </ng-content>
  `,
})
export class PasswordInputComponent extends PasswordInputRootDirective {
  /**
   * ARIA label applied to the input element. Use this if you omit the {@link
   * label}
   *
   * @since 2.9.0
   */
  readonly ariaLabel = input<string | undefined>(undefined, {
    alias: "aria-label",
  })

  /**
   * ID reference for an external label applied to the input element.
   *
   * @since 2.9.0
   */
  readonly ariaLabelledby = input<string | undefined>(undefined, {
    alias: "aria-labelledby",
  })

  /**
   * When `true`, renders a clear button that resets the input value on click.
   * The button only appears when the input has a value.
   *
   * @default true
   */
  readonly clearable = input<boolean | undefined, Booleanish>(true, {
    transform: booleanAttribute,
  })

  /**
   * Optional error that describes the element when {@link invalid} is true.
   *
   * @remarks
   * To customize the element, provide it using the directive instead:
   *
   * ```angular-html
   * <div q-text-input-error-text>...</div>
   * ```
   */
  readonly errorText = input<string | undefined | null>()

  /**
   * Optional hint describing the element. This element is automatically
   * associated with the component's input element for accessibility.
   *
   * @remarks
   * To customize the element, provide it using the directive instead:
   *
   * ```angular-html
   * <div q-text-input-hint>...</div>
   * ```
   */
  readonly hint = input<string | undefined | null>()

  /**
   * Optional label describing the element. Recommended. This element is
   * automatically associated with the component's input element for
   * accessibility.
   *
   * @remarks
   * To customize the element, provide it using the directive instead:
   *
   * ```angular-html
   * <div q-text-input-label>...</div>
   * ```
   */
  readonly label = input<string | undefined>()

  /**
   * HTML {@link https://www.w3schools.com/tags/att_input_placeholder.asp placeholder} attribute,
   * passed to the internal input element.
   */
  readonly placeholder = input<string>("")

  /**
   * {@link https://lucide.dev lucide-angular} icon, positioned before
   * the input.
   *
   * @remarks
   * To customize the element, provide it using the directive instead:
   *
   * ```angular-html
   * <q-password-input>
   *   <div q-input-start-icon [icon]="..."></div>
   * </q-password-input>
   * ```
   */
  override readonly startIcon = input<LucideIconOrString | undefined>()

  readonly computedErrorText = computed(() => {
    const errorTextInput = this.errorText()
    const errorTextFromControl = this.formControlContext.errorText()
    return errorTextInput ?? errorTextFromControl ?? null
  })
}
