// packages/frameworks/angular/src/file-input/file-input.component.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {booleanAttribute, Component, input} from "@angular/core"

import {provideQdsFileUploadContext} from "@qualcomm-ui/angular/file-upload"
import {provideQdsInputContext} from "@qualcomm-ui/angular/input"
import {provideFileUploadContext} from "@qualcomm-ui/angular-core/file-upload"
import type {Booleanish} from "@qualcomm-ui/utils/coercion"

import {FileInputRootDirective} from "./file-input-root.directive"

/**
 * @since next-release
 */
@Component({
  providers: [
    provideFileUploadContext(),
    provideQdsInputContext(),
    provideQdsFileUploadContext(),
  ],
  selector: "q-file-input",
  standalone: false,
  template: `
    <ng-content select="[q-file-input-label]">
      @if (label()) {
        <label q-file-input-label>{{ label() }}</label>
      }
    </ng-content>

    <ng-content select="[q-file-input-control]">
      <div q-file-input-control>
        <ng-content select="[q-file-input-display]">
          <span q-file-input-display [placeholder]="placeholder()"></span>
        </ng-content>

        <ng-content select="[q-file-input-clear-trigger]">
          @if (clearable()) {
            <button q-file-input-clear-trigger></button>
          }
        </ng-content>
      </div>
    </ng-content>

    <ng-content select="[q-file-input-hidden-input]">
      <input q-file-input-hidden-input />
    </ng-content>

    <ng-content select="[q-file-input-error-text]">
      @if (errorText()) {
        <div q-file-input-error-text>
          {{ errorText() }}
        </div>
      }
    </ng-content>
  `,
})
export class FileInputComponent extends FileInputRootDirective {
  /**
   * When `true`, renders a clear button that resets the selected file on click.
   * The button only appears when a file has been selected.
   *
   * @default true
   */
  readonly clearable = input<boolean | undefined, Booleanish>(true, {
    transform: booleanAttribute,
  })

  /**
   * Optional error message that describes the element when {@link invalid} is true.
   *
   * @remarks
   * To customize the element, provide it using the directive instead:
   *
   * ```angular-html
   * <div q-file-input-error-text>...</div>
   * ```
   */
  readonly errorText = input<string | undefined>()

  /**
   * Optional label describing the file input. This element is automatically
   * associated with the hidden file input for accessibility.
   *
   * @remarks
   * To customize the element, provide it using the directive instead:
   *
   * ```angular-html
   * <label q-file-input-label>...</label>
   * ```
   */
  readonly label = input<string | undefined>()

  /**
   * Text shown when no file has been selected.
   */
  readonly placeholder = input<string | undefined>()
}

// packages/frameworks/react/src/file-input/file-input.tsx
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {ReactElement, ReactNode} from "react"

import {useControlledId} from "@qualcomm-ui/react-core/state"

import {
  FileInputClearTrigger,
  type FileInputClearTriggerProps,
} from "./file-input-clear-trigger"
import {
  FileInputControl,
  type FileInputControlProps,
} from "./file-input-control"
import {
  FileInputDisplay,
  type FileInputDisplayProps,
} from "./file-input-display"
import {
  FileInputErrorText,
  type FileInputErrorTextProps,
} from "./file-input-error-text"
import {
  FileInputHiddenInput,
  type FileInputHiddenInputProps,
} from "./file-input-hidden-input"
import {FileInputLabel, type FileInputLabelProps} from "./file-input-label"
import {FileInputRoot, type FileInputRootProps} from "./file-input-root"

export interface FileInputProps extends FileInputRootProps {
  /**
   * The simple FileInput doesn't support children.
   */
  children?: never

  /**
   * When `true`, renders a clear button that resets the selected file on click.
   * The button only appears when a file has been selected.
   *
   * @default true
   */
  clearable?: boolean

  clearTriggerProps?: FileInputClearTriggerProps

  /**
   * Props applied to the visible input-like control.
   */
  controlProps?: FileInputControlProps

  /**
   * Props applied to the selected file name display.
   */
  displayProps?: FileInputDisplayProps

  /**
   * Optional error message that describes the element when {@link invalid} is true.
   */
  errorText?: ReactNode

  /**
   * Props applied to the error text element.
   */
  errorTextProps?: FileInputErrorTextProps

  /**
   * Props applied to the hidden file input element.
   */
  hiddenInputProps?: FileInputHiddenInputProps

  /**
   * Optional label describing the file input. This element is automatically
   * associated with the hidden file input for accessibility.
   */
  label?: ReactNode

  /**
   * Props applied to the label element.
   */
  labelProps?: FileInputLabelProps

  /**
   * Text shown when no file has been selected.
   */
  placeholder?: ReactNode
}

/**
 * @since next-release
 */
export function FileInput({
  clearable = true,
  clearTriggerProps,
  controlProps,
  displayProps,
  errorText,
  errorTextProps,
  hiddenInputProps,
  label,
  labelProps,
  placeholder,
  ...props
}: FileInputProps): ReactElement {
  const labelContent = label || labelProps?.children
  const errorTextContent = errorText || errorTextProps?.children

  const ids = {
    clearTrigger: useControlledId(clearTriggerProps?.id),
    errorText: useControlledId(errorTextProps?.id),
    hiddenInput: useControlledId(hiddenInputProps?.id),
    label: useControlledId(labelProps?.id),
    root: useControlledId(props.id),
    ...props.ids,
  }

  return (
    <FileInputRoot {...props} id={ids.root} ids={ids}>
      {labelContent ? (
        <FileInputLabel {...labelProps} id={ids.label}>
          {labelContent}
        </FileInputLabel>
      ) : null}

      <FileInputControl {...controlProps}>
        <FileInputDisplay placeholder={placeholder} {...displayProps} />
        {clearable ? (
          <FileInputClearTrigger {...clearTriggerProps} id={ids.clearTrigger} />
        ) : null}
      </FileInputControl>

      <FileInputHiddenInput {...hiddenInputProps} id={ids.hiddenInput} />

      {errorTextContent ? (
        <FileInputErrorText {...errorTextProps} id={ids.errorText}>
          {errorTextContent}
        </FileInputErrorText>
      ) : null}
    </FileInputRoot>
  )
}
