// packages/debug-apps/react-ssr/src/routes/components+/avatar+/_avatar.tsx
import {AvatarContentDemo as ContentDemo} from "@qualcomm-ui/react-docs/components+/avatar+/demos/avatar-content-demo"
import {AvatarShowcaseDemo as ShowcaseDemo} from "@qualcomm-ui/react-docs/components+/avatar+/demos/avatar-showcase-demo"
import {AvatarSizeDemo as SizeDemo} from "@qualcomm-ui/react-docs/components+/avatar+/demos/avatar-size-demo"
import {AvatarStateCallbackDemo as StateCallbackDemo} from "@qualcomm-ui/react-docs/components+/avatar+/demos/avatar-state-callback-demo"
import {AvatarStatusDemo as StatusDemo} from "@qualcomm-ui/react-docs/components+/avatar+/demos/avatar-status-demo"
import {AvatarVariantDemo as VariantDemo} from "@qualcomm-ui/react-docs/components+/avatar+/demos/avatar-variant-demo"

const demos = [
  {component: ContentDemo, title: "Content"},
  {component: ShowcaseDemo, title: "Showcase"},
  {component: SizeDemo, title: "Size"},
  {component: StateCallbackDemo, title: "State Callback"},
  {component: StatusDemo, title: "Status"},
  {component: VariantDemo, title: "Variant"},
]

export default function AvatarDemos() {
  return (
    <div className="page">
      {demos.map(({component: Demo, title}) => (
        <div className="section" key={title}>
          <h2 className="section-title">{title}</h2>
          <div className="demo-container">
            <Demo />
          </div>
        </div>
      ))}
    </div>
  )
}

// packages/debug-apps/angular-ssr/src/app/components/avatar.ts
import {Component} from "@angular/core"

import {AvatarContentDemo} from "@qualcomm-ui/angular-docs/components+/avatar+/demos/avatar-content-demo"
import {AvatarEmphasisDemo} from "@qualcomm-ui/angular-docs/components+/avatar+/demos/avatar-emphasis-demo"
import {AvatarShowcaseDemo} from "@qualcomm-ui/angular-docs/components+/avatar+/demos/avatar-showcase-demo"
import {AvatarSizeDemo} from "@qualcomm-ui/angular-docs/components+/avatar+/demos/avatar-size-demo"
import {AvatarStateCallbackDemo} from "@qualcomm-ui/angular-docs/components+/avatar+/demos/avatar-state-callback-demo"
import {AvatarStatusDemo} from "@qualcomm-ui/angular-docs/components+/avatar+/demos/avatar-status-demo"

@Component({
  imports: [
    AvatarContentDemo,
    AvatarEmphasisDemo,
    AvatarShowcaseDemo,
    AvatarSizeDemo,
    AvatarStateCallbackDemo,
    AvatarStatusDemo,
  ],
  selector: "app-avatar",
  template: `
    <div class="container">
      <div class="section">
        <h2 class="section-title">Content</h2>
        <div class="demo-container">
          <avatar-content />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Emphasis</h2>
        <div class="demo-container">
          <avatar-emphasis />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Showcase</h2>
        <div class="demo-container">
          <avatar-showcase />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Size</h2>
        <div class="demo-container">
          <avatar-size />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">State Callback</h2>
        <div class="demo-container">
          <avatar-state-callback />
        </div>
      </div>
      <div class="section">
        <h2 class="section-title">Status</h2>
        <div class="demo-container">
          <avatar-status />
        </div>
      </div>
    </div>
  `,
})
export class AvatarPage {}
