// packages/docs/angular-docs/src/routes/components+/collapsible+/demos/collapsible-explorer-demo.ts
import {Component} from "@angular/core"

import {ButtonModule} from "@qualcomm-ui/angular/button"
import {CollapsibleModule} from "@qualcomm-ui/angular/collapsible"

@Component({
  imports: [CollapsibleModule, ButtonModule],
  selector: "collapsible-explorer-demo",
  template: `
    <div
      class="flex flex-col items-center"
      q-collapsible-root
      [defaultOpen]="true"
    >
      <button
        class="my-3"
        emphasis="primary"
        q-button
        q-collapsible-trigger
        variant="fill"
      >
        Toggle
      </button>
      <div q-collapsible-content>
        <div
          class="border-neutral-01 flex h-24 w-72 flex-col rounded-sm border p-4"
        >
          Content
        </div>
      </div>
    </div>
  `,
})
export class CollapsibleExplorerDemo {}

// packages/docs/react-docs/src/routes/components+/collapsible+/demos/collapsible-explorer-demo.tsx
import type {ReactElement} from "react"

import {Button} from "@qualcomm-ui/react/button"
import {Collapsible} from "@qualcomm-ui/react/collapsible"

export function CollapsibleExplorerDemo(): ReactElement {
  return (
    <Collapsible.Root className="flex flex-col items-center" defaultOpen>
      <Collapsible.Trigger
        className="my-3"
        render={<Button emphasis="primary" />}
      >
        Toggle
      </Collapsible.Trigger>
      <Collapsible.Content>
        <div className="border-neutral-01 flex h-24 w-72 flex-col rounded-sm border p-4">
          Content
        </div>
      </Collapsible.Content>
    </Collapsible.Root>
  )
}
