// packages/docs/angular-docs/src/routes/components+/badges+/text-badge+/demos/text-badge-variant-demo.ts
import {Component} from "@angular/core"

import {BadgeDirective} from "@qualcomm-ui/angular/badge"

@Component({
  imports: [BadgeDirective],
  selector: "text-badge-variant-demo",
  template: `
    <div class="flex flex-col gap-4">
      <div class="flex flex-wrap items-center gap-2">
        <span emphasis="neutral" q-badge variant="subtle">neutral</span>
        <span emphasis="brand" q-badge variant="subtle">brand</span>
        <span emphasis="info" q-badge variant="subtle">info</span>
        <span emphasis="success" q-badge variant="subtle">success</span>
        <span emphasis="warning" q-badge variant="subtle">warning</span>
        <span emphasis="danger" q-badge variant="subtle">danger</span>
      </div>
      <div class="flex flex-wrap items-center gap-2">
        <span emphasis="blue" q-badge variant="subtle">blue</span>
        <span emphasis="cyan" q-badge variant="subtle">cyan</span>
        <span emphasis="green" q-badge variant="subtle">green</span>
        <span emphasis="kiwi" q-badge variant="subtle">kiwi</span>
        <span emphasis="magenta" q-badge variant="subtle">magenta</span>
        <span emphasis="orange" q-badge variant="subtle">orange</span>
        <span emphasis="purple" q-badge variant="subtle">purple</span>
        <span emphasis="red" q-badge variant="subtle">red</span>
        <span emphasis="teal" q-badge variant="subtle">teal</span>
        <span emphasis="yellow" q-badge variant="subtle">yellow</span>
      </div>
    </div>
  `,
})
export class TextBadgeVariantDemo {}

// packages/docs/react-docs/src/routes/components+/badges+/text-badge+/demos/text-badge-variant-demo.tsx
import type {ReactElement} from "react"

import {Badge} from "@qualcomm-ui/react/badge"

export function TextBadgeVariantDemo(): ReactElement {
  return (
    <div className="flex flex-col gap-4">
      <div className="flex flex-wrap items-center gap-2">
        <Badge emphasis="neutral" variant="subtle">
          neutral
        </Badge>
        <Badge emphasis="brand" variant="subtle">
          brand
        </Badge>
        <Badge emphasis="info" variant="subtle">
          info
        </Badge>
        <Badge emphasis="success" variant="subtle">
          success
        </Badge>
        <Badge emphasis="warning" variant="subtle">
          warning
        </Badge>
        <Badge emphasis="danger" variant="subtle">
          danger
        </Badge>
      </div>
      <div className="flex flex-wrap items-center gap-2">
        <Badge emphasis="blue" variant="subtle">
          blue
        </Badge>
        <Badge emphasis="cyan" variant="subtle">
          cyan
        </Badge>
        <Badge emphasis="green" variant="subtle">
          green
        </Badge>
        <Badge emphasis="kiwi" variant="subtle">
          kiwi
        </Badge>
        <Badge emphasis="magenta" variant="subtle">
          magenta
        </Badge>
        <Badge emphasis="orange" variant="subtle">
          orange
        </Badge>
        <Badge emphasis="purple" variant="subtle">
          purple
        </Badge>
        <Badge emphasis="red" variant="subtle">
          red
        </Badge>
        <Badge emphasis="teal" variant="subtle">
          teal
        </Badge>
        <Badge emphasis="yellow" variant="subtle">
          yellow
        </Badge>
      </div>
    </div>
  )
}
