// packages/docs/react-docs/src/routes/components+/number-input+/demos/number-input-unit-select-demo.tsx
import type {ReactElement} from "react"

import {NumberInput, type UnitOption} from "@qualcomm-ui/react/number-input"

const currencyOptions: UnitOption[] = [
  {displayText: "$ (USD)", label: "$", value: "USD"},
  {displayText: "£ (GBP)", label: "£", value: "GBP"},
  {displayText: "€ (EUR)", label: "€", value: "EUR"},
]

export function NumberInputUnitSelectDemo(): ReactElement {
  return (
    // preview
    <NumberInput
      className="w-72"
      defaultUnit="USD"
      label="Price"
      placeholder="0.00"
      unitOptions={currencyOptions}
      value="0"
    />
    // preview
  )
}

// packages/docs/angular-docs/src/routes/components+/number-input+/demos/number-input-unit-select-demo.ts
import {Component} from "@angular/core"

import {
  NumberInputModule,
  type UnitOption,
} from "@qualcomm-ui/angular/number-input"

@Component({
  imports: [NumberInputModule],
  selector: "number-input-unit-select-demo",
  template: `
    <!-- preview -->
    <q-number-input
      class="w-72"
      defaultUnit="USD"
      label="Price"
      placeholder="0.00"
      [unitOptions]="unitOptions"
    />
    <!-- preview -->
  `,
})
export class NumberInputUnitSelectDemo {
  unitOptions: UnitOption[] = [
    {displayText: "$ (USD)", label: "$", value: "USD"},
    {displayText: "£ (GBP)", label: "£", value: "GBP"},
    {displayText: "€ (EUR)", label: "€", value: "EUR"},
  ]
}
