// packages/docs/react-docs/src/routes/components+/alert-banner+/demos/alert-banner-dismissable-demo.tsx
import {type ReactElement, useState} from "react"

import {AlertBanner} from "@qualcomm-ui/react/alert-banner"
import {Button} from "@qualcomm-ui/react/button"

export function AlertBannerDismissableDemo(): ReactElement {
  const [simpleVisible, setSimpleVisible] = useState(true)
  const [compositeVisible, setCompositeVisible] = useState(true)

  const allDismissed = !simpleVisible && !compositeVisible

  return (
    <div className="flex w-full flex-col gap-4">
      {/* preview */}
      {simpleVisible && (
        <AlertBanner
          closeButtonAriaLabel="Close this banner"
          dismissable
          heading="Simple API"
          onClose={() => setSimpleVisible(false)}
        />
      )}

      {compositeVisible && (
        <AlertBanner.Root
          closeButtonAriaLabel="Close this banner"
          onClose={() => setCompositeVisible(false)}
          variant="subtle"
        >
          <AlertBanner.Icon />
          <AlertBanner.Heading>Composite API</AlertBanner.Heading>
          <AlertBanner.CloseButton />
        </AlertBanner.Root>
      )}
      {/* preview */}
      {allDismissed && (
        <Button
          onClick={() => {
            setSimpleVisible(true)
            setCompositeVisible(true)
          }}
        >
          Reset demo
        </Button>
      )}
    </div>
  )
}

// packages/docs/angular-docs/src/routes/components+/alert-banner+/demos/alert-banner-dismissable-demo.ts
import {Component} from "@angular/core"

import {AlertBannerModule} from "@qualcomm-ui/angular/alert-banner"
import {ButtonModule} from "@qualcomm-ui/angular/button"

@Component({
  imports: [AlertBannerModule, ButtonModule],
  selector: "alert-banner-dismissable-demo",
  template: `
    <div class="flex w-full flex-col gap-4">
      <!-- preview -->
      @if (simpleVisible) {
        <div
          closeButtonAriaLabel="Close this banner"
          dismissable
          heading="Simple API"
          q-alert-banner
          (closed)="simpleVisible = false"
        ></div>
      }

      @if (compositeVisible) {
        <div
          closeButtonAriaLabel="Close this banner"
          q-alert-banner-root
          variant="subtle"
          (closed)="compositeVisible = false"
        >
          <span q-alert-banner-icon></span>
          <div q-alert-banner-heading>Composite API</div>
          <button q-alert-banner-close-button></button>
        </div>
      }
      <!-- preview -->

      @if (!simpleVisible && !compositeVisible) {
        <button q-button (click)="reset()">Reset demo</button>
      }
    </div>
  `,
})
export class AlertBannerDismissableDemo {
  simpleVisible = true
  compositeVisible = true

  reset() {
    this.simpleVisible = true
    this.compositeVisible = true
  }
}
