// packages/docs/react-docs/src/routes/components+/alert-banner+/demos/alert-banner-simple-demo.tsx
import type {ReactElement} from "react"

import {AlertBanner} from "@qualcomm-ui/react/alert-banner"
import {Button} from "@qualcomm-ui/react/button"

export function AlertBannerSimpleDemo(): ReactElement {
  return (
    // preview
    <AlertBanner
      action={
        <Button emphasis="white-persistent" size="sm" variant="outline">
          Action
        </Button>
      }
      description="Description"
      dismissable
      heading="Heading"
      onClose={() => console.log("close")}
    />
    // preview
  )
}

// packages/docs/angular-docs/src/routes/components+/alert-banner+/demos/alert-banner-simple-demo.ts
import {Component} from "@angular/core"

import {AlertBannerModule} from "@qualcomm-ui/angular/alert-banner"
import {ButtonModule} from "@qualcomm-ui/angular/button"

@Component({
  imports: [AlertBannerModule, ButtonModule],
  selector: "alert-banner-simple-demo",
  template: `
    <!-- preview -->
    <div
      description="Description"
      dismissable
      heading="Heading"
      q-alert-banner
      (closed)="onClose()"
    >
      <button
        emphasis="white-persistent"
        q-alert-banner-action
        q-button
        size="sm"
        variant="outline"
      >
        Action
      </button>
    </div>
    <!-- preview -->
  `,
})
export class AlertBannerSimpleDemo {
  onClose() {
    console.log("close")
  }
}
