// packages/docs/react-docs/src/routes/components+/alert-banner+/demos/alert-banner-emphasis-demo.tsx
import type {ReactElement} from "react"

import {AlertBanner} from "@qualcomm-ui/react/alert-banner"

export function AlertBannerEmphasisDemo(): ReactElement {
  return (
    <div className="grid w-full gap-4">
      {/* preview */}
      <AlertBanner emphasis="info" heading="info" />
      <AlertBanner emphasis="success" heading="success" />
      <AlertBanner emphasis="warning" heading="warning" />
      <AlertBanner emphasis="danger" heading="danger" />
      <AlertBanner emphasis="neutral" heading="neutral" />
      {/* preview */}
    </div>
  )
}

// packages/docs/angular-docs/src/routes/components+/alert-banner+/demos/alert-banner-emphasis-demo.ts
import {Component} from "@angular/core"

import {AlertBannerModule} from "@qualcomm-ui/angular/alert-banner"

@Component({
  imports: [AlertBannerModule],
  selector: "alert-banner-emphasis-demo",
  template: `
    <div class="grid w-full gap-4">
      <!-- preview -->
      <div emphasis="info" heading="info" q-alert-banner></div>
      <div emphasis="success" heading="success" q-alert-banner></div>
      <div emphasis="warning" heading="warning" q-alert-banner></div>
      <div emphasis="danger" heading="danger" q-alert-banner></div>
      <div emphasis="neutral" heading="neutral" q-alert-banner></div>
      <!-- preview -->
    </div>
  `,
})
export class AlertBannerEmphasisDemo {}
