// packages/docs/react-docs/src/routes/components+/alert-banner+/demos/alert-banner-explorer-demo.tsx
import type {ReactElement} from "react"

import {AlertBanner} from "@qualcomm-ui/react/alert-banner"
import {Button} from "@qualcomm-ui/react/button"

export function AlertBannerExplorerDemo(): ReactElement {
  return (
    <AlertBanner
      action={
        <Button emphasis="neutral" size="sm" variant="outline">
          Action
        </Button>
      }
      description="Description"
      dismissable
      heading="Heading"
      variant="subtle"
    />
  )
}

// packages/docs/angular-docs/src/routes/components+/alert-banner+/demos/alert-banner-explorer-demo.ts
import {Component} from "@angular/core"

import {AlertBannerModule} from "@qualcomm-ui/angular/alert-banner"
import {ButtonModule} from "@qualcomm-ui/angular/button"

@Component({
  imports: [AlertBannerModule, ButtonModule],
  selector: "alert-banner-explorer-demo",
  template: `
    <!-- preview -->
    <div
      description="Description"
      dismissable
      heading="Heading"
      q-alert-banner
      variant="subtle"
    >
      <button
        emphasis="neutral"
        q-alert-banner-action
        q-button
        size="sm"
        variant="outline"
      >
        Action
      </button>
    </div>
    <!-- preview -->
  `,
})
export class AlertBannerExplorerDemo {}
