// packages/docs/react-docs/src/routes/components+/alert-banner+/demos/alert-banner-composite-demo.tsx
import type {ReactElement} from "react"

import {AlertBanner} from "@qualcomm-ui/react/alert-banner"
import {Button} from "@qualcomm-ui/react/button"

export function AlertBannerCompositeDemo(): ReactElement {
  return (
    // preview
    <AlertBanner.Root onClose={() => console.log("close")}>
      <AlertBanner.Icon />
      <AlertBanner.Heading>Heading</AlertBanner.Heading>
      <AlertBanner.Description>Description</AlertBanner.Description>
      <AlertBanner.ActionContainer>
        <Button emphasis="white-persistent" size="sm" variant="outline">
          Action
        </Button>
      </AlertBanner.ActionContainer>
      <AlertBanner.CloseButton />
    </AlertBanner.Root>
    // preview
  )
}

// packages/docs/angular-docs/src/routes/components+/alert-banner+/demos/alert-banner-composite-demo.ts
import {Component} from "@angular/core"

import {AlertBannerModule} from "@qualcomm-ui/angular/alert-banner"
import {ButtonModule} from "@qualcomm-ui/angular/button"

@Component({
  imports: [AlertBannerModule, ButtonModule],
  selector: "alert-banner-composite-demo",
  template: `
    <!-- preview -->
    <div q-alert-banner-root (closed)="onClose()">
      <span q-alert-banner-icon></span>
      <div q-alert-banner-heading>Heading</div>
      <div q-alert-banner-description>Description</div>
      <div q-alert-banner-action>
        <button
          emphasis="white-persistent"
          q-button
          size="sm"
          variant="outline"
        >
          Action
        </button>
      </div>
      <button q-alert-banner-close-button></button>
    </div>
    <!-- preview -->
  `,
})
export class AlertBannerCompositeDemo {
  onClose() {
    console.log("close")
  }
}
