// packages/docs/react-docs/src/routes/components+/alert-banner+/demos/alert-banner-action-demo.tsx
import type {ReactElement} from "react"

import {AlertBanner} from "@qualcomm-ui/react/alert-banner"
import {Button} from "@qualcomm-ui/react/button"

export function AlertBannerActionDemo(): ReactElement {
  return (
    <div className="flex w-full flex-col gap-4">
      {/* preview */}
      <AlertBanner
        action={
          <Button emphasis="white-persistent" size="sm" variant="outline">
            Take action
          </Button>
        }
        description="Use white-persistent emphasis for strong variant"
        heading="Strong"
        variant="strong"
      />

      <AlertBanner
        action={
          <Button emphasis="neutral" size="sm" variant="outline">
            Take action
          </Button>
        }
        description="Use neutral emphasis for subtle variant"
        heading="Subtle"
        variant="subtle"
      />
      {/* preview */}
    </div>
  )
}

// packages/docs/angular-docs/src/routes/components+/alert-banner+/demos/alert-banner-action-demo.ts
import {Component} from "@angular/core"

import {AlertBannerModule} from "@qualcomm-ui/angular/alert-banner"
import {ButtonModule} from "@qualcomm-ui/angular/button"

@Component({
  imports: [AlertBannerModule, ButtonModule],
  selector: "alert-banner-action-demo",
  template: `
    <div class="flex w-full flex-col gap-4">
      <!-- preview -->
      <div
        description="Use white-persistent emphasis for strong variant"
        heading="Strong"
        q-alert-banner
        variant="strong"
      >
        <button
          emphasis="white-persistent"
          q-alert-banner-action
          q-button
          size="sm"
          variant="outline"
        >
          Take action
        </button>
      </div>

      <div
        description="Use neutral emphasis for subtle variant"
        heading="Subtle"
        q-alert-banner
        variant="subtle"
      >
        <button
          emphasis="neutral"
          q-alert-banner-action
          q-button
          size="sm"
          variant="outline"
        >
          Take action
        </button>
      </div>
      <!-- preview -->
    </div>
  `,
})
export class AlertBannerActionDemo {}
