// packages/docs/react-docs/src/routes/components+/menu+/demos/menu-button-demo.tsx
import type {ReactElement} from "react"

import {
  Copy,
  Ellipsis,
  File,
  FileText,
  FolderOpen,
  Pencil,
  Trash2,
} from "lucide-react"

import {Menu} from "@qualcomm-ui/react/menu"
import {Portal} from "@qualcomm-ui/react-core/portal"

export function MenuButtonDemo(): ReactElement {
  return (
    <div className="flex gap-2.5">
      <Menu.Root positioning={{placement: "bottom-end"}}>
        <Menu.Trigger>
          <Menu.Button emphasis="primary" startIcon={File}>
            File
          </Menu.Button>
        </Menu.Trigger>
        <Portal>
          <Menu.Positioner>
            <Menu.Content>
              <Menu.Item value="new-text-file">
                <Menu.ItemStartIcon icon={FileText} />
                New Text File
              </Menu.Item>
              <Menu.Item value="new-file">
                <Menu.ItemStartIcon icon={File} />
                New File...
              </Menu.Item>
              <Menu.Item value="open-file">
                <Menu.ItemStartIcon icon={FolderOpen} />
                Open File...
              </Menu.Item>
            </Menu.Content>
          </Menu.Positioner>
        </Portal>
      </Menu.Root>

      <Menu.Root size="sm">
        <Menu.Trigger>
          <Menu.IconButton
            aria-label="More actions"
            emphasis="primary"
            icon={Ellipsis}
          />
        </Menu.Trigger>
        <Portal>
          <Menu.Positioner>
            <Menu.Content>
              <Menu.Item value="rename">
                <Menu.ItemStartIcon icon={Pencil} />
                Rename
              </Menu.Item>
              <Menu.Item value="duplicate">
                <Menu.ItemStartIcon icon={Copy} />
                Duplicate
              </Menu.Item>
              <Menu.Item value="delete">
                <Menu.ItemStartIcon icon={Trash2} />
                Delete
              </Menu.Item>
            </Menu.Content>
          </Menu.Positioner>
        </Portal>
      </Menu.Root>
    </div>
  )
}

// packages/docs/angular-docs/src/routes/components+/menu+/demos/menu-button-demo.ts
import {Component} from "@angular/core"
import {
  Copy,
  Ellipsis,
  File,
  FileText,
  FolderOpen,
  Pencil,
  Trash2,
} from "lucide-angular"

import {MenuModule} from "@qualcomm-ui/angular/menu"
import {provideIcons} from "@qualcomm-ui/angular-core/lucide"
import {PortalComponent} from "@qualcomm-ui/angular-core/portal"

@Component({
  imports: [MenuModule, PortalComponent],
  providers: [
    provideIcons({Copy, Ellipsis, File, FileText, FolderOpen, Pencil, Trash2}),
  ],
  selector: "menu-button-demo",
  template: `
    <div class="flex gap-2.5">
      <q-menu [positioning]="{placement: 'bottom-end'}">
        <button emphasis="primary" q-menu-button startIcon="File">File</button>
        <q-portal>
          <div q-menu-positioner>
            <div q-menu-content>
              <button q-menu-item value="new-text-file">
                <div icon="FileText" q-menu-item-start-icon></div>
                New Text File
              </button>
              <button q-menu-item value="new-file">
                <div icon="File" q-menu-item-start-icon></div>
                New File...
              </button>
              <button q-menu-item value="open-file">
                <div icon="FolderOpen" q-menu-item-start-icon></div>
                Open File...
              </button>
            </div>
          </div>
        </q-portal>
      </q-menu>

      <q-menu size="sm">
        <button
          aria-label="More actions"
          emphasis="primary"
          icon="Ellipsis"
          q-menu-icon-button
        ></button>
        <q-portal>
          <div q-menu-positioner>
            <div q-menu-content>
              <button q-menu-item value="rename">
                <div icon="Pencil" q-menu-item-start-icon></div>
                Rename
              </button>
              <button q-menu-item value="duplicate">
                <div icon="Copy" q-menu-item-start-icon></div>
                Duplicate
              </button>
              <button q-menu-item value="delete">
                <div icon="Trash2" q-menu-item-start-icon></div>
                Delete
              </button>
            </div>
          </div>
        </q-portal>
      </q-menu>
    </div>
  `,
})
export class MenuButtonDemo {}
