// packages/docs/angular-docs/src/routes/components+/switch+/demos/switch-sizes-demo.ts
import {Component} from "@angular/core"

import {SwitchModule} from "@qualcomm-ui/angular/switch"

@Component({
  imports: [SwitchModule],
  selector: "switch-sizes-demo",
  template: `
    <div class="flex flex-col items-start gap-4">
      <!-- preview -->
      <label label="Small (sm)" q-switch size="sm"></label>
      <label label="Medium (md)" q-switch size="md"></label>
      <label label="Large (lg)" q-switch size="lg"></label>
      <!-- preview -->
    </div>
  `,
})
export class SwitchSizesDemo {}

// packages/docs/react-docs/src/routes/components+/switch+/demos/switch-sizes-demo.tsx
import type {ReactElement} from "react"

import {Switch} from "@qualcomm-ui/react/switch"

export function SwitchSizesDemo(): ReactElement {
  return (
    <div className="grid justify-center gap-4">
      {/* preview */}
      <Switch label="Small (sm)" size="sm" />
      <Switch label="Medium (md)" size="md" />
      <Switch label="Large (lg)" size="lg" />
      {/* preview */}
    </div>
  )
}
