// packages/docs/react-docs/src/routes/components+/segmented-control+/demos/segmented-control-controlled-demo.tsx
import {useState} from "react"

import {SegmentedControl} from "@qualcomm-ui/react/segmented-control"

export function SegmentedControlControlledDemo() {
  const [value, setValue] = useState<string[] | null | undefined>(null)

  return (
    // preview
    <SegmentedControl.Root
      multiple
      onValueChange={(values) => {
        console.log("Selected values:", values?.length ? values : "<none>")
        setValue(values)
      }}
      value={value}
    >
      <SegmentedControl.Item text="Production" value="prod" />
      <SegmentedControl.Item text="Staging" value="staging" />
      <SegmentedControl.Item text="Development" value="dev" />
      <SegmentedControl.Item text="QA" value="qa" />
    </SegmentedControl.Root>
    // preview
  )
}

// packages/docs/angular-docs/src/routes/components+/segmented-control+/demos/segmented-control-controlled-demo.ts
import {Component, signal} from "@angular/core"

import {SegmentedControlModule} from "@qualcomm-ui/angular/segmented-control"

@Component({
  imports: [SegmentedControlModule],
  selector: "segmented-control-controlled-demo",
  template: `
    <!-- preview -->
    <fieldset
      multiple
      q-segmented-control
      [value]="value()"
      (valueChanged)="valueChanged($event)"
    >
      <label q-segmented-control-item text="Production" value="prod"></label>
      <label q-segmented-control-item text="Staging" value="staging"></label>
      <label q-segmented-control-item text="Development" value="dev"></label>
      <label q-segmented-control-item text="QA" value="qa"></label>
    </fieldset>
    <!-- preview -->
  `,
})
export class SegmentedControlControlledDemo {
  readonly value = signal<string[] | null | undefined>([])

  valueChanged(newValue: string[] | null | undefined) {
    console.log("Selected values", newValue?.length ? newValue : "<none>")
    this.value.set(newValue)
  }
}
