// packages/docs/angular-docs/src/routes/components+/text-input+/demos/text-input-composite-demo.ts
import {Component} from "@angular/core"

import {TextInputModule} from "@qualcomm-ui/angular/text-input"

@Component({
  imports: [TextInputModule],
  selector: "text-input-composite-demo",
  template: `
    <!-- preview -->
    <div class="w-72" q-text-input-root>
      <label q-text-input-label>Label</label>
      <div q-text-input-input-group>
        <input placeholder="Placeholder text" q-text-input-input />
        <button q-text-input-clear-trigger></button>
        <span q-text-input-error-indicator></span>
      </div>
      <div q-text-input-hint>Optional hint</div>
    </div>
    <!-- preview -->
  `,
})
export class TextInputCompositeDemo {}

// packages/docs/react-docs/src/routes/components+/text-input+/demos/text-input-composite-demo.tsx
import type {ReactElement} from "react"

import {AArrowDown} from "lucide-react"

import {TextInput} from "@qualcomm-ui/react/text-input"

export function TextInputCompositeDemo(): ReactElement {
  return (
    // preview
    <TextInput.Root className="w-72" startIcon={AArrowDown}>
      <TextInput.Label>Label</TextInput.Label>
      <TextInput.InputGroup>
        <TextInput.Input placeholder="Placeholder text" />
        <TextInput.ErrorIndicator />
      </TextInput.InputGroup>
      <TextInput.Hint>Optional hint</TextInput.Hint>
      <TextInput.ErrorText>Optional error text</TextInput.ErrorText>
    </TextInput.Root>
    // preview
  )
}
