// packages/docs/angular-docs/src/routes/components+/text-area+/demos/text-area-sizes-demo.ts
import {Component} from "@angular/core"

import {TextAreaModule} from "@qualcomm-ui/angular/text-area"

@Component({
  imports: [TextAreaModule],
  selector: "text-area-sizes-demo",
  template: `
    <div class="flex flex-col items-start gap-4">
      <!-- preview -->
      <q-text-area class="w-56" defaultValue="sm" size="sm" />
      <q-text-area class="w-60" defaultValue="md" />
      <q-text-area class="w-64" defaultValue="lg" size="lg" />
      <!-- preview -->
    </div>
  `,
})
export class TextAreaSizesDemo {}

// packages/docs/react-docs/src/routes/components+/text-area+/demos/text-area-sizes-demo.tsx
import type {ReactElement} from "react"

import {TextArea} from "@qualcomm-ui/react/text-area"

export function TextAreaSizesDemo(): ReactElement {
  return (
    <div className="flex flex-col items-start gap-4">
      {/* preview */}
      <TextArea className="w-56" defaultValue="sm" size="sm" />
      <TextArea className="w-60" defaultValue="md" />
      <TextArea className="w-64" defaultValue="lg" size="lg" />
      {/* preview */}
    </div>
  )
}
