// packages/docs/angular-docs/src/routes/components+/text-area+/demos/text-area-composite-demo.ts
import {Component} from "@angular/core"

import {TextAreaModule} from "@qualcomm-ui/angular/text-area"

@Component({
  imports: [TextAreaModule],
  selector: "text-area-composite-demo",
  template: `
    <!-- preview -->
    <div class="w-72" q-text-area-root>
      <label q-text-area-label>Label</label>
      <div q-text-area-counter></div>
      <textarea placeholder="Placeholder text" q-text-area-input></textarea>
      <div q-text-area-hint>Optional hint</div>
      <div q-text-area-error-text>Optional error text</div>
    </div>
    <!-- preview -->
  `,
})
export class TextAreaCompositeDemo {}

// packages/docs/react-docs/src/routes/components+/text-area+/demos/text-area-composite-demo.tsx
import type {ReactElement} from "react"

import {TextArea} from "@qualcomm-ui/react/text-area"

export function TextAreaCompositeDemo(): ReactElement {
  return (
    // preview
    <TextArea.Root className="w-72" maxLength={50}>
      <TextArea.Label>Label</TextArea.Label>
      <TextArea.Counter />
      <TextArea.Input placeholder="Placeholder text" />
      <TextArea.Hint>Optional hint</TextArea.Hint>
      <TextArea.ErrorText>Optional error text</TextArea.ErrorText>
    </TextArea.Root>
    // preview
  )
}
