// packages/docs/angular-docs/src/routes/components+/text-area+/demos/text-area-simple-demo.ts
import {Component} from "@angular/core"

import {TextAreaModule} from "@qualcomm-ui/angular/text-area"

@Component({
  imports: [TextAreaModule],
  selector: "text-area-simple-demo",
  template: `
    <!-- preview -->
    <q-text-area
      class="w-72"
      hint="Optional hint"
      label="Label"
      placeholder="Placeholder text"
    />
    <!-- preview -->
  `,
})
export class TextAreaSimpleDemo {}

// packages/docs/react-docs/src/routes/components+/text-area+/demos/text-area-simple-demo.tsx
import type {ReactElement} from "react"

import {TextArea} from "@qualcomm-ui/react/text-area"

export function TextAreaSimpleDemo(): ReactElement {
  return (
    // preview
    <TextArea
      className="w-72"
      hint="Optional hint"
      label="Label"
      placeholder="Placeholder text"
    />
    // preview
  )
}
