// packages/docs/angular-docs/src/routes/components+/text-area+/demos/text-area-states-demo.ts
import {Component} from "@angular/core"

import {TextAreaModule} from "@qualcomm-ui/angular/text-area"

@Component({
  imports: [TextAreaModule],
  selector: "text-area-states-demo",
  template: `
    <div class="flex w-72 flex-col gap-4">
      <!-- preview -->
      <q-text-area disabled label="Disabled" placeholder="Disabled" />
      <q-text-area label="Read only" placeholder="Read only" readOnly />
      <q-text-area
        errorText="Invalid"
        invalid
        label="Invalid"
        placeholder="Invalid"
      />
      <!-- preview -->
    </div>
  `,
})
export class TextAreaStatesDemo {}

// packages/docs/react-docs/src/routes/components+/text-area+/demos/text-area-states-demo.tsx
import type {ReactElement} from "react"

import {TextArea} from "@qualcomm-ui/react/text-area"

export function TextAreaStatesDemo(): ReactElement {
  return (
    <div className="flex w-72 flex-col gap-4">
      {/* preview */}
      <TextArea disabled label="Disabled" placeholder="Disabled" />
      <TextArea label="Read only" placeholder="Read only" readOnly />
      <TextArea label="Required" placeholder="Required" required />
      <TextArea
        errorText="Invalid"
        invalid
        label="Invalid"
        placeholder="Invalid"
      />
      {/* preview */}
    </div>
  )
}
