// packages/frameworks/angular/src/radio/radio.component.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {Component, input} from "@angular/core"

import {provideRadioItemContext} from "@qualcomm-ui/angular-core/radio"

import {provideQdsRadioContext} from "./qds-radio-context.service"
import {RadioRootDirective} from "./radio-root.directive"

@Component({
  providers: [provideRadioItemContext(), provideQdsRadioContext()],
  selector: "[q-radio]",
  standalone: false,
  template: `
    <ng-content select="[q-radio-hidden-input]">
      <input q-radio-hidden-input />
    </ng-content>
    <ng-content select="[q-radio-control]">
      <div q-radio-control></div>
    </ng-content>
    <ng-content select="[q-radio-label]">
      @if (label()) {
        <span q-radio-label>
          {{ label() }}
        </span>
      }
    </ng-content>
    <ng-content select="[q-radio-error-text]">
      @if (errorText()) {
        <div q-radio-error-text>
          {{ errorText() }}
        </div>
      }
    </ng-content>
    <ng-content select="[q-radio-hint]">
      @if (hint()) {
        <div q-radio-hint>
          {{ hint() }}
        </div>
      }
    </ng-content>
  `,
})
export class RadioComponent extends RadioRootDirective {
  /**
   * Optional error that describes the radio when the field is invalid. This
   * element is automatically associated with the radio for accessibility.
   *
   * @remarks
   * To customize the element, provide it using the directive instead:
   *
   * ```angular-html
   * <label q-radio>
   *   <div q-radio-error-text>...</div>
   * </label>
   * ```
   */
  readonly errorText = input<string>()

  /**
   * Optional hint text displayed below the radio. Hints are hidden when the
   * radio is invalid.
   *
   * @remarks
   * To customize the element, provide it using the directive instead:
   *
   * ```angular-html
   * <label q-radio>
   *   <div q-radio-hint>...</div>
   * </label>
   * ```
   */
  readonly hint = input<string>()

  /**
   * Optional label describing the element. Recommended. This element is
   * automatically associated with the component's input element for accessibility.
   *
   * @remarks
   * To customize the element, provide it using the directive instead:
   *
   * ```angular-html
   * <label q-radio>
   *   <div q-radio-label>...</div>
   * </label>
   * ```
   */
  readonly label = input<string | undefined>()
}

// packages/frameworks/react/src/radio/radio.tsx
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {ReactElement, ReactNode} from "react"

import {RadioControl, type RadioControlProps} from "./radio-control"
import {RadioErrorText, type RadioErrorTextProps} from "./radio-error-text"
import {
  RadioHiddenInput,
  type RadioHiddenInputProps,
} from "./radio-hidden-input"
import {RadioHint, type RadioHintProps} from "./radio-hint"
import {RadioLabel, type RadioLabelProps} from "./radio-label"
import {RadioRoot, type RadioRootProps} from "./radio-root"

export interface RadioProps extends RadioRootProps {
  /**
   * {@link https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-label aria-label}
   * attribute, forwarded to the hidden input element.
   */
  "aria-label"?: string | undefined

  /**
   * {@link https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-labelledby aria-labelledby}
   * attribute, forwarded to the hidden input element. If you provide a {@link
   * label}, omit this prop.
   */
  "aria-labelledby"?: string | undefined

  /**
   * The simple Radio doesn't support children.
   */
  children?: never

  /**
   * Props applied to the control element.
   * @inheritDoc
   */
  controlProps?: RadioControlProps

  /**
   * Optional error that describes the element when invalid.
   */
  errorText?: string

  /**
   * Props applied to the error text element.
   * @inheritDoc
   */
  errorTextProps?: RadioErrorTextProps

  /**
   * Props applied to the hidden input element.
   * @inheritDoc
   */
  hiddenInputProps?: RadioHiddenInputProps

  /**
   * Optional hint text that describes the element.
   */
  hint?: ReactNode

  /**
   * Props applied to the hint element.
   * @inheritDoc
   */
  hintProps?: RadioHintProps

  /**
   * Optional label describing the element. Recommended. This element is
   * automatically associated with the component's input element for
   * accessibility.
   */
  label?: ReactNode

  /**
   * Props applied to the label element.
   * @inheritDoc
   */
  labelProps?: RadioLabelProps
}

export function Radio({
  "aria-label": ariaLabel,
  "aria-labelledby": ariaLabelledBy,
  controlProps,
  errorText,
  errorTextProps,
  hiddenInputProps: hiddenInputPropsProp,
  hint,
  hintProps,
  label,
  labelProps,
  ...props
}: RadioProps): ReactElement {
  const labelContent = label || labelProps?.children
  const errorTextContent = errorText || errorTextProps?.children
  const hintContent = hint || hintProps?.children

  const hiddenInputProps = {
    ...hiddenInputPropsProp,
  }

  if (ariaLabel !== undefined) {
    hiddenInputProps["aria-label"] = ariaLabel
  }
  if (ariaLabelledBy !== undefined) {
    hiddenInputProps["aria-labelledby"] = ariaLabelledBy
  }

  return (
    <RadioRoot {...props}>
      <RadioHiddenInput {...hiddenInputProps} />
      <RadioControl {...controlProps} />
      {labelContent ? (
        <RadioLabel {...labelProps}>{labelContent}</RadioLabel>
      ) : null}
      {hintContent ? <RadioHint {...hintProps}>{hintContent}</RadioHint> : null}
      {errorTextContent ? (
        <RadioErrorText {...errorTextProps}>{errorTextContent}</RadioErrorText>
      ) : null}
    </RadioRoot>
  )
}
