// packages/frameworks/react/src/checkbox/checkbox.tsx
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {ReactElement, ReactNode} from "react"

import type {CheckboxElementIds} from "@qualcomm-ui/core/checkbox"
import {useOptionalContentId} from "@qualcomm-ui/react-core/machine"
import {useControlledId} from "@qualcomm-ui/react-core/state"

import {CheckboxControl, type CheckboxControlProps} from "./checkbox-control"
import {
  CheckboxErrorText,
  type CheckboxErrorTextProps,
} from "./checkbox-error-text"
import {
  CheckboxHiddenInput,
  type CheckboxHiddenInputProps,
} from "./checkbox-hidden-input"
import {
  CheckboxIndicator,
  type CheckboxIndicatorProps,
} from "./checkbox-indicator"
import {CheckboxLabel, type CheckboxLabelProps} from "./checkbox-label"
import {CheckboxRoot, type CheckboxRootProps} from "./checkbox-root"

export interface CheckboxProps extends CheckboxRootProps {
  /**
   * {@link https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-label aria-label}
   * attribute, forwarded to the hidden input element.
   */
  "aria-label"?: string | undefined

  /**
   * {@link https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-labelledby aria-labelledby}
   * attribute, forwarded to the hidden input element. If you provide a {@link
   * label}, omit this prop.
   */
  "aria-labelledby"?: string | undefined

  /**
   * The simple Checkbox doesn't support children.
   */
  children?: never

  /**
   * Props applied to the control element.
   * @inheritDoc
   */
  controlProps?: CheckboxControlProps

  /**
   * Optional error that describes the element when {@link invalid} is true.
   */
  errorText?: string

  /**
   * Props applied to the error text element.
   * @inheritDoc
   */
  errorTextProps?: CheckboxErrorTextProps

  /**
   * Props applied to the hidden input element.
   * @inheritDoc
   */
  hiddenInputProps?: CheckboxHiddenInputProps

  /**
   * Props applied to the indicator element.
   * @inheritDoc
   */
  indicatorProps?: CheckboxIndicatorProps

  /**
   * Optional label describing the element. Recommended. This element is
   * automatically associated with the component's input element for
   * accessibility.
   */
  label?: ReactNode

  /**
   * Props applied to the label element.
   * @inheritDoc
   */
  labelProps?: CheckboxLabelProps
}

export function Checkbox({
  "aria-label": ariaLabel,
  "aria-labelledby": ariaLabelledBy,
  controlProps,
  errorText,
  errorTextProps,
  hiddenInputProps,
  indicatorProps,
  label,
  labelProps,
  ...props
}: CheckboxProps): ReactElement {
  const labelContent = label || labelProps?.children
  const errorTextContent = errorText || errorTextProps?.children

  const ids: Partial<CheckboxElementIds> = {
    errorText: useOptionalContentId(errorTextContent, errorTextProps),
    hiddenInput: useControlledId(hiddenInputProps?.id),
    label: useOptionalContentId(labelContent, labelProps),
    root: useControlledId(props.id),
    ...props.ids,
  }

  return (
    <CheckboxRoot {...props} id={ids.root} ids={ids}>
      <CheckboxHiddenInput
        aria-label={ariaLabel}
        aria-labelledby={ariaLabelledBy}
        {...hiddenInputProps}
        id={ids.hiddenInput}
      />
      <CheckboxControl {...controlProps}>
        <CheckboxIndicator {...indicatorProps} />
      </CheckboxControl>
      {labelContent ? (
        <CheckboxLabel {...labelProps} id={ids.label}>
          {labelContent}
        </CheckboxLabel>
      ) : null}
      {errorTextContent ? (
        <CheckboxErrorText {...errorTextProps} id={ids.errorText}>
          {errorTextContent}
        </CheckboxErrorText>
      ) : null}
    </CheckboxRoot>
  )
}

// packages/frameworks/angular/src/checkbox/checkbox.component.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {Component, input} from "@angular/core"

import {provideCheckboxContext} from "@qualcomm-ui/angular-core/checkbox"

import {CheckboxRootDirective} from "./checkbox-root.directive"
import {provideQdsCheckboxContext} from "./qds-checkbox-context.service"

@Component({
  host: {
    "[attr.aria-label]": "undefined",
    "[attr.aria-labelledby]": "undefined",
  },
  providers: [provideCheckboxContext(), provideQdsCheckboxContext()],
  selector: "[q-checkbox]",
  standalone: false,
  template: `
    <ng-content select="[q-checkbox-hidden-input]">
      <input
        q-checkbox-hidden-input
        [aria-label]="ariaLabel()"
        [aria-labelledby]="ariaLabelledby()"
      />
    </ng-content>

    <ng-content select="[q-checkbox-control]">
      <div q-checkbox-control>
        <div q-checkbox-indicator></div>
      </div>
    </ng-content>
    <ng-content select="[q-checkbox-label]">
      @if (label()) {
        <span q-checkbox-label>
          {{ label() }}
        </span>
      }
    </ng-content>
    <ng-content select="[q-checkbox-error-text]">
      @if (errorText()) {
        <div q-checkbox-error-text>
          {{ errorText() }}
        </div>
      }
    </ng-content>
    <ng-content select="[q-checkbox-hint]">
      @if (hint()) {
        <div q-checkbox-hint>
          {{ hint() }}
        </div>
      }
    </ng-content>
  `,
})
export class CheckboxComponent extends CheckboxRootDirective {
  /**
   * Accessible label applied to the generated hidden input when no visible label
   * is provided.
   *
   * @since next-release
   */
  readonly ariaLabel = input<string | undefined>(undefined, {
    alias: "aria-label",
  })

  /**
   * ID reference for an external label applied to the generated hidden input.
   *
   * @since next-release
   */
  readonly ariaLabelledby = input<string | undefined>(undefined, {
    alias: "aria-labelledby",
  })

  /**
   * Optional error that describes the checkbox when the field is invalid. This
   * element is automatically associated with the checkbox for accessibility.
   *
   * @remarks
   * To customize the element, provide it using the directive instead:
   *
   * ```angular-html
   * <label q-checkbox>
   *   <div q-checkbox-error-text>...</div>
   * </label>
   * ```
   */
  readonly errorText = input<string>()

  /**
   * Optional hint text displayed below the checkbox. Hints are hidden when the
   * checkbox is invalid.
   *
   * @remarks
   * To customize the element, provide it using the directive instead:
   *
   * ```angular-html
   * <label q-checkbox>
   *   <div q-checkbox-hint>...</div>
   * </label>
   * ```
   */
  readonly hint = input<string>()

  /**
   * Optional label describing the checkbox. This element is automatically
   * associated with the checkbox for accessibility. If omitted, you should provide
   * an `aria-label` or `aria-labelledby` attribute on the `q-checkbox-hidden-input`
   * element.
   *
   * @remarks
   * To customize the element, provide it using the directive instead:
   *
   * ```angular-html
   * <label q-checkbox>
   *   <div q-checkbox-label>...</div>
   * </label>
   * ```
   */
  readonly label = input<string | undefined>()
}
