// packages/docs/angular-docs/src/routes/components+/number-input+/demos/number-input-sizes-demo.ts
import {Component} from "@angular/core"
import {Sigma} from "lucide-angular"

import {NumberInputModule} from "@qualcomm-ui/angular/number-input"
import {provideIcons} from "@qualcomm-ui/angular-core/lucide"

@Component({
  imports: [NumberInputModule],
  providers: [provideIcons({Sigma})],
  selector: "number-input-sizes-demo",
  template: `
    <div class="flex flex-col items-start gap-4">
      <!-- preview -->
      <q-number-input
        aria-label="Number input with size sm"
        class="w-56"
        placeholder="sm"
        size="sm"
        startIcon="Sigma"
      />
      <q-number-input
        aria-label="Number input with size md"
        class="w-64"
        placeholder="md"
        size="md"
        startIcon="Sigma"
      />
      <q-number-input
        aria-label="Number input with size lg"
        class="w-72"
        placeholder="lg"
        size="lg"
        startIcon="Sigma"
      />
      <!-- preview -->
    </div>
  `,
})
export class NumberInputSizesDemo {}

// packages/docs/react-docs/src/routes/components+/number-input+/demos/number-input-sizes-demo.tsx
import type {ReactElement} from "react"

import {Sigma} from "lucide-react"

import {NumberInput} from "@qualcomm-ui/react/number-input"

export function NumberInputSizesDemo(): ReactElement {
  return (
    <div className="flex flex-col items-start gap-4">
      {/* preview */}
      <NumberInput
        aria-label="sm demo"
        className="w-56"
        placeholder="sm"
        size="sm"
        startIcon={Sigma}
      />
      <NumberInput
        aria-label="md demo"
        className="w-64"
        placeholder="md"
        startIcon={Sigma}
      />
      <NumberInput
        aria-label="lg demo"
        className="w-72"
        placeholder="lg"
        size="lg"
        startIcon={Sigma}
      />
      {/* preview */}
    </div>
  )
}
