// packages/frameworks/react/src/combobox/combobox.tsx
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {ReactElement, ReactNode} from "react"

import {useOptionalContentId} from "@qualcomm-ui/react-core/machine"
import {Portal, type PortalProps} from "@qualcomm-ui/react-core/portal"
import {useControlledId} from "@qualcomm-ui/react-core/state"
import type {CollectionItem} from "@qualcomm-ui/utils/collection"

import {
  ComboboxClearTrigger,
  type ComboboxClearTriggerProps,
} from "./combobox-clear-trigger"
import {ComboboxContent, type ComboboxContentProps} from "./combobox-content"
import {ComboboxControl, type ComboboxControlProps} from "./combobox-control"
import {ComboboxEmpty, type ComboboxEmptyProps} from "./combobox-empty"
import {
  ComboboxErrorIndicator,
  type ComboboxErrorIndicatorProps,
} from "./combobox-error-indicator"
import {
  ComboboxErrorText,
  type ComboboxErrorTextProps,
} from "./combobox-error-text"
import {ComboboxHint, type ComboboxHintProps} from "./combobox-hint"
import {ComboboxInput, type ComboboxInputProps} from "./combobox-input"
import {type ComboboxItemRenderProp, ComboboxItems} from "./combobox-items"
import {ComboboxLabel, type ComboboxLabelProps} from "./combobox-label"
import {
  ComboboxPositioner,
  type ComboboxPositionerProps,
} from "./combobox-positioner"
import {ComboboxRoot, type ComboboxRootProps} from "./combobox-root"
import {ComboboxTrigger, type ComboboxTriggerProps} from "./combobox-trigger"
import {ComboboxVirtualContent} from "./combobox-virtual-content"

export interface ComboboxProps<T extends CollectionItem>
  extends ComboboxRootProps<T> {
  /**
   * {@link https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-label aria-label}
   * attribute, forwarded to the input element.
   */
  "aria-label"?: string | undefined

  /**
   * {@link https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-labelledby aria-labelledby}
   * attribute, forwarded to the input element. If you provide a {@link label},
   * omit this prop.
   */
  "aria-labelledby"?: string | undefined

  /**
   * Props applied to the clear trigger element. To prevent this element from
   * rendering, pass `{hidden: true}`
   *
   * @inheritDoc
   */
  clearTriggerProps?: ComboboxClearTriggerProps

  /**
   * Props applied to the content element.
   *
   * @inheritDoc
   */
  contentProps?: ComboboxContentProps

  /**
   * Props applied to the control element.
   *
   * @inheritDoc
   */
  controlProps?: ComboboxControlProps

  /**
   * Label to render when the list is empty.
   *
   * @default "No results found"
   */
  emptyMessage?: ReactNode

  /**
   * Props applied to the component that renders the empty message.
   */
  emptyProps?: ComboboxEmptyProps

  /**
   * Props applied to the error indicator element.
   *
   * @inheritDoc
   */
  errorIndicatorProps?: ComboboxErrorIndicatorProps

  /**
   * Optional error that describes the element when {@link invalid} is true.
   */
  errorText?: string

  /**
   * Props applied to the error text element.
   *
   * @inheritDoc
   */
  errorTextProps?: ComboboxErrorTextProps

  /**
   * Set to `true` to highlight option text matches during filtering.
   */
  highlightMatchingText?: boolean

  /**
   * Optional hint describing the element. This element is automatically
   * associated with the component's input element for accessibility.
   */
  hint?: ReactNode

  /**
   * Props applied to the label element.
   *
   * @inheritDoc
   */
  hintProps?: ComboboxHintProps

  /**
   * Props applied to the select element.
   *
   * @inheritDoc
   */
  inputProps?: ComboboxInputProps

  /**
   * Optional label describing the element. Recommended. This element is
   * automatically associated with the component's input element for
   * accessibility.
   */
  label?: ReactNode

  /**
   * Props applied to the label element.
   *
   * @inheritDoc
   */
  labelProps?: ComboboxLabelProps

  /**
   * Props applied to the portal element.
   *
   * @inheritDoc
   */
  portalProps?: PortalProps

  /**
   * Props applied to the positioner element.
   *
   * @inheritDoc
   */
  positionerProps?: ComboboxPositionerProps

  /**
   * Customize the rendering of the combobox list items.
   */
  renderItem?: ComboboxItemRenderProp<T>

  /**
   * Props applied to the trigger element.
   *
   * @inheritDoc
   */
  triggerProps?: ComboboxTriggerProps

  /**
   * When `true`, the list items will be virtually rendered. Useful for large lists.
   */
  virtual?: boolean
}

export function Combobox<T extends CollectionItem = CollectionItem>({
  "aria-label": ariaLabel,
  "aria-labelledby": ariaLabelledBy,
  clearTriggerProps,
  contentProps,
  controlProps,
  emptyMessage,
  emptyProps,
  errorIndicatorProps,
  errorText,
  errorTextProps,
  highlightMatchingText,
  hint,
  hintProps,
  inputProps,
  label,
  labelProps,
  portalProps,
  positionerProps,
  renderItem,
  triggerProps,
  virtual,
  ...props
}: ComboboxProps<T>): ReactElement {
  const emptyContent =
    emptyMessage || emptyProps?.children || "No results found"
  const labelContent = label || labelProps?.children
  const hintContent = hint || hintProps?.children
  const errorTextContent = errorText || errorTextProps?.children

  const ids = {
    clearTrigger: useOptionalContentId(
      !clearTriggerProps?.hidden,
      clearTriggerProps,
    ),
    content: useControlledId(contentProps?.id),
    control: useControlledId(controlProps?.id),
    errorText: useOptionalContentId(errorTextContent, errorTextProps),
    hint: useOptionalContentId(hintContent, hintProps),
    input: useControlledId(inputProps?.id),
    label: useOptionalContentId(labelContent, labelProps),
    positioner: useControlledId(positionerProps?.id),
    root: useControlledId(props.id),
    ...props.ids,
  }

  return (
    <ComboboxRoot {...props} ids={ids}>
      {labelContent ? (
        <ComboboxLabel {...labelProps} id={ids.label}>
          {labelContent}
        </ComboboxLabel>
      ) : null}
      <ComboboxControl {...controlProps} id={ids.control}>
        <ComboboxInput
          aria-label={ariaLabel}
          aria-labelledby={ariaLabelledBy}
          {...inputProps}
          id={ids.input}
        />
        <ComboboxClearTrigger {...clearTriggerProps} id={ids.clearTrigger} />
        <ComboboxErrorIndicator {...errorIndicatorProps} />
        <ComboboxTrigger {...triggerProps} id={ids.trigger} />
      </ComboboxControl>
      <Portal {...portalProps}>
        <ComboboxPositioner {...positionerProps} id={ids.positioner}>
          {virtual ? (
            <ComboboxVirtualContent
              {...contentProps}
              highlightMatchingText={highlightMatchingText}
              id={ids.content}
              renderItem={renderItem}
            >
              <ComboboxEmpty {...emptyProps}>{emptyContent}</ComboboxEmpty>
            </ComboboxVirtualContent>
          ) : (
            <ComboboxContent {...contentProps} id={ids.content}>
              <ComboboxEmpty {...emptyProps}>{emptyContent}</ComboboxEmpty>
              <ComboboxItems
                highlightMatchingText={highlightMatchingText}
                renderItem={renderItem}
              />
            </ComboboxContent>
          )}
        </ComboboxPositioner>
      </Portal>

      {errorTextContent ? (
        <ComboboxErrorText {...errorTextProps} id={ids.errorText}>
          {errorTextContent}
        </ComboboxErrorText>
      ) : null}

      {hintContent ? (
        <ComboboxHint {...hintProps} id={ids.hint}>
          {hintContent}
        </ComboboxHint>
      ) : null}
    </ComboboxRoot>
  )
}

// packages/frameworks/angular/src/combobox/combobox.component.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {
  booleanAttribute,
  ChangeDetectionStrategy,
  Component,
  computed,
  contentChild,
  input,
} from "@angular/core"

import {provideQdsInputContext} from "@qualcomm-ui/angular/input"
import {provideComboboxContext} from "@qualcomm-ui/angular-core/combobox"
import {providePresenceContext} from "@qualcomm-ui/angular-core/presence"
import type {Booleanish} from "@qualcomm-ui/utils/coercion"

import {ComboboxContentDirective} from "./combobox-content.directive"
import {ComboboxRootDirective} from "./combobox-root.directive"
import {ComboboxVirtualContentDirective} from "./combobox-virtual-content.directive"
import {provideQdsComboboxContext} from "./qds-combobox-context.service"

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "[attr.aria-label]": "undefined",
    "[attr.aria-labelledby]": "undefined",
  },
  providers: [
    provideComboboxContext(),
    provideQdsComboboxContext(),
    provideQdsInputContext(),
    providePresenceContext(),
  ],
  selector: "q-combobox",
  standalone: false,
  template: `
    <ng-content select="[q-combobox-label]">
      @if (label()) {
        <div q-combobox-label>{{ label() }}</div>
      }
    </ng-content>

    <ng-content select="[q-combobox-control]">
      <div q-combobox-control>
        <ng-content select="[q-combobox-icon]" />
        <ng-content select="[q-combobox-input]">
          <input
            q-combobox-input
            [aria-label]="ariaLabel()"
            [aria-labelledby]="ariaLabelledby()"
            [placeholder]="placeholder()"
          />
        </ng-content>
        <ng-content select="[q-combobox-clear-trigger]">
          @if (clearable()) {
            <button q-combobox-clear-trigger></button>
          }
        </ng-content>
        <ng-content select="[q-combobox-trigger]">
          <button q-combobox-trigger></button>
        </ng-content>
        <ng-content select="[q-combobox-error-indicator]">
          <div q-combobox-error-indicator></div>
        </ng-content>
      </div>
    </ng-content>

    <ng-content select="[q-combobox-hint]">
      @if (hint()) {
        <div q-combobox-hint>{{ hint() }}</div>
      }
    </ng-content>

    <ng-content select="[q-combobox-error-text]">
      @if (errorText()) {
        <div q-combobox-error-text>{{ errorText() }}</div>
      }
    </ng-content>

    <ng-template qPortal [disabled]="disablePortal()">
      <div q-combobox-positioner>
        @if (shouldRenderCustom()) {
          <ng-content select="[q-combobox-content]" />
        } @else if (shouldRenderVirtual()) {
          <ng-content select="[q-combobox-virtual-content]" />
        } @else {
          @if (virtual()) {
            <div q-combobox-virtual-content>
              <ng-content select="[q-combobox-empty]">
                @if (emptyText()) {
                  <div q-combobox-empty>{{ emptyText() }}</div>
                }
              </ng-content>
              <ng-container *comboboxVirtualizer="let virtualizer">
                @for (
                  virtualItem of virtualizer.getVirtualItems();
                  track virtualItem.index
                ) {
                  @let item = collection().items.at(virtualItem.index);
                  <div q-combobox-virtual-item [virtualItem]="virtualItem">
                    @if (highlightMatchingText()) {
                      <span
                        ignoreCase
                        q-combobox-item-text
                        q-highlight
                        [query]="comboboxContext.context().inputValue"
                        [text]="collection().stringifyItem(item)"
                      ></span>
                    } @else {
                      <span q-combobox-item-text>
                        {{ collection().stringifyItem(item) }}
                      </span>
                    }
                    <span q-combobox-item-indicator></span>
                  </div>
                }
              </ng-container>
            </div>
          } @else {
            <div q-combobox-content>
              <ng-content select="[q-combobox-empty]">
                @if (emptyText()) {
                  <div q-combobox-empty>{{ emptyText() }}</div>
                }
              </ng-content>
              @for (
                item of collection().items;
                track collection().getItemValue(item)
              ) {
                <div q-combobox-item [item]="item">
                  @if (highlightMatchingText()) {
                    <span
                      ignoreCase
                      q-combobox-item-text
                      q-highlight
                      [query]="comboboxContext.context().inputValue"
                      [text]="collection().stringifyItem(item)"
                    ></span>
                  } @else {
                    <span q-combobox-item-text>
                      {{ collection().stringifyItem(item) }}
                    </span>
                  }
                  <span q-combobox-item-indicator></span>
                </div>
              }
            </div>
          }
        }
      </div>
    </ng-template>
  `,
})
export class ComboboxComponent extends ComboboxRootDirective {
  /**
   * ARIA label applied to the control element. Use this if you omit the {@link
   * label}
   *
   * @since 2.9.0
   */
  readonly ariaLabel = input<string | undefined>(undefined, {
    alias: "aria-label",
  })

  /**
   * ID reference for an external label applied to the input element.
   *
   * @since 2.9.0
   */
  readonly ariaLabelledby = input<string | undefined>(undefined, {
    alias: "aria-labelledby",
  })

  /**
   * When `true`, renders a clear button that resets the input value on click.
   * The button only appears when the input has a value.
   *
   * @default true
   */
  readonly clearable = input<boolean | undefined, Booleanish>(true, {
    transform: booleanAttribute,
  })

  /**
   * Set to true to disable portalling behavior for the combobox dropdown content.
   */
  readonly disablePortal = input<boolean | undefined, Booleanish>(undefined, {
    transform: booleanAttribute,
  })

  /**
   * Text to display when no items match the filter.
   *
   * @default 'No results found'
   */
  readonly emptyText = input<string | undefined | null>("No results found")

  /**
   * Optional error that describes the element when {@link invalid} is true.
   *
   * @remarks
   * To customize the element, provide it using the directive instead:
   *
   * ```angular-html
   * <div q-combobox-error-text>...</div>
   * ```
   */
  readonly errorText = input<string | undefined | null>()

  /**
   * Optional hint describing the element. This element is automatically
   * associated with the component's input element for accessibility.
   *
   * @remarks
   * To customize the element, provide it using the directive instead:
   *
   * ```angular-html
   * <div q-combobox-hint>...</div>
   * ```
   */
  readonly hint = input<string | undefined | null>()

  /**
   * Set to `true` to highlight option text matches during filtering.
   */
  readonly highlightMatchingText = input<boolean | undefined, Booleanish>(
    undefined,
    {
      transform: booleanAttribute,
    },
  )

  /**
   * Optional label describing the element. Recommended. This element is
   * automatically associated with the component's input element for
   * accessibility.
   *
   * @remarks
   * To customize the element, provide it using the directive instead:
   *
   * ```angular-html
   * <div q-combobox-label>...</div>
   * ```
   */
  readonly label = input<string | undefined>()

  /**
   * When `true`, the list items will be virtually rendered. Useful for large lists.
   */
  readonly virtual = input<boolean | undefined, Booleanish>(undefined, {
    transform: booleanAttribute,
  })

  protected readonly customContent = contentChild(ComboboxContentDirective)
  protected readonly customVirtualContent = contentChild(
    ComboboxVirtualContentDirective,
  )
  protected readonly shouldRenderCustom = computed(() => !!this.customContent())
  protected readonly shouldRenderVirtual = computed(
    () => !!this.customVirtualContent(),
  )
}
