// packages/docs/react-docs/src/routes/components+/combobox+/demos/combobox-error-demo.tsx
import {useState} from "react"

import type {ComboboxInputValueChangeDetails} from "@qualcomm-ui/core/combobox"
import {Combobox} from "@qualcomm-ui/react/combobox"
import {useListCollection} from "@qualcomm-ui/react-core/collection"
import {useFilter} from "@qualcomm-ui/react-core/locale"

import {countries} from "./country-list"

export function ComboboxErrorDemo() {
  const {contains} = useFilter({sensitivity: "base"})
  const [value, setValue] = useState<string[]>([])

  const {collection, filter} = useListCollection({
    filter: contains,
    initialItems: countries,
  })

  function handleInputChange(details: ComboboxInputValueChangeDetails) {
    filter(details.inputValue)
  }

  return (
    // preview
    <Combobox
      aria-label="Country"
      className="w-48"
      collection={collection}
      errorText="You must select a country"
      invalid={!value.length}
      onInputValueChange={handleInputChange}
      onValueChange={(details) => setValue(details.value)}
      placeholder="Select a country"
      value={value}
    />
    // preview
  )
}

// packages/docs/angular-docs/src/routes/components+/combobox+/demos/combobox-error-demo.ts
import {Component} from "@angular/core"

import {ComboboxModule} from "@qualcomm-ui/angular/combobox"
import {useListCollection} from "@qualcomm-ui/angular-core/collection"
import type {ComboboxInputValueChangeDetails} from "@qualcomm-ui/core/combobox"

import {countries} from "./country-list"

@Component({
  imports: [ComboboxModule],
  selector: "combobox-error-demo",
  template: `
    <!-- preview -->
    <q-combobox
      aria-label="Country"
      class="w-48"
      errorText="You must select a country"
      invalid
      placeholder="Select a country"
      [collection]="listCollection.collection()"
      (inputValueChanged)="onInputChange($event)"
    />
    <!-- preview -->
  `,
})
export class ComboboxErrorDemo {
  readonly listCollection = useListCollection<string>({
    filter: "contains",
    items: countries,
  })

  onInputChange(event: ComboboxInputValueChangeDetails) {
    this.listCollection.filterText.set(event.inputValue)
  }
}
