// packages/docs/angular-docs/src/routes/components+/slider+/demos/slider-explorer-demo.ts
import {Component} from "@angular/core"

import {SliderModule} from "@qualcomm-ui/angular/slider"

@Component({
  imports: [SliderModule],
  selector: "slider-explorer-demo",
  template: `
    <q-slider
      class="sm:w-80"
      hint="Some contextual help here"
      label="Choose a value"
      [defaultValue]="[25]"
    />
  `,
})
export class SliderExplorerDemo {}

// packages/docs/react-docs/src/routes/components+/slider+/demos/slider-explorer-demo.tsx
import type {ReactElement} from "react"

import {Slider} from "@qualcomm-ui/react/slider"

export function SliderExplorerDemo(): ReactElement {
  return (
    <Slider
      className="sm:w-80"
      defaultValue={[25]}
      hint="Some contextual help here"
      label="Choose a value"
    />
  )
}
