// packages/docs/react-docs/src/routes/components+/tree+/demos/tree-valid-state-demo.tsx
import {createTreeCollection} from "@qualcomm-ui/core/tree"
import {Tree} from "@qualcomm-ui/react/tree"

interface Node {
  id: string
  name: string
  nodes?: Node[]
}

export function TreeValidStateDemo() {
  return (
    // preview
    <Tree.Root
      className="w-full max-w-sm"
      collection={collection}
      // [!code highlight]
      defaultCheckedValue={["elite", "plus"]}
      defaultExpandedValue={["qualcomm", "sdx"]}
    >
      {/* preview */}
      {collection.rootNode.nodes?.map((node, index) => {
        return (
          <Tree.Nodes
            key={node.id}
            indexPath={[index]}
            node={node}
            renderBranch={({node}) => (
              <Tree.BranchNode>
                <Tree.BranchTrigger />
                <Tree.NodeCheckbox />
                <Tree.NodeText>{node.name}</Tree.NodeText>
              </Tree.BranchNode>
            )}
            renderLeaf={({node}) => (
              <Tree.LeafNode>
                <Tree.NodeCheckbox />
                <Tree.NodeText>{node.name}</Tree.NodeText>
              </Tree.LeafNode>
            )}
          />
        )
      })}
    </Tree.Root>
  )
}

const collection = createTreeCollection<Node>({
  rootNode: {
    id: "ROOT",
    name: "",
    nodes: [
      {
        id: "qualcomm",
        name: "Qualcomm",
        nodes: [
          {
            id: "sdx",
            name: "Snapdragon X",
            nodes: [
              {id: "elite", name: "Snapdragon X Elite"},
              {id: "plus", name: "Snapdragon X Plus"},
            ],
          },
        ],
      },
    ],
  },
})

// packages/docs/angular-docs/src/routes/components+/tree+/demos/tree-valid-state-demo.ts
import {Component} from "@angular/core"

import {TreeModule} from "@qualcomm-ui/angular/tree"
import {createTreeCollection} from "@qualcomm-ui/core/tree"

interface Node {
  id: string
  name: string
  nodes?: Node[]
}

@Component({
  imports: [TreeModule],
  selector: "tree-valid-state-demo",
  template: `
    <!-- preview -->
    <div
      class="w-full max-w-sm"
      q-tree-root
      [collection]="collection"
      [defaultCheckedValue]="['elite', 'plus']"
      [defaultExpandedValue]="['qualcomm', 'sdx']"
    >
      <!-- preview -->
      @for (
        node of collection.rootNode.nodes;
        let i = $index;
        track collection.getNodeValue(node)
      ) {
        <q-tree-nodes [indexPath]="[i]" [node]="node">
          <ng-template
            let-branch
            q-tree-branch-template
            [rootNode]="collection.rootNode"
          >
            <div q-tree-branch-node>
              <div q-tree-branch-trigger></div>
              <span q-tree-node-checkbox></span>
              <span q-tree-node-text>{{ branch.node.name }}</span>
            </div>
          </ng-template>

          <ng-template
            let-leaf
            q-tree-leaf-template
            [rootNode]="collection.rootNode"
          >
            <div q-tree-leaf-node>
              <span q-tree-node-checkbox></span>
              <span q-tree-node-text>{{ leaf.node.name }}</span>
            </div>
          </ng-template>
        </q-tree-nodes>
      }
    </div>
  `,
})
export class TreeValidStateDemo {
  collection = createTreeCollection<Node>({
    rootNode: {
      id: "ROOT",
      name: "",
      nodes: [
        {
          id: "qualcomm",
          name: "Qualcomm",
          nodes: [
            {
              id: "sdx",
              name: "Snapdragon X",
              nodes: [
                {id: "elite", name: "Snapdragon X Elite"},
                {id: "plus", name: "Snapdragon X Plus"},
              ],
            },
          ],
        },
      ],
    },
  })
}
