// packages/docs/react-docs/src/routes/components+/tree+/demos/tree-filtering-demo.tsx
import {type ReactElement, useState} from "react"

import {FileText, FolderIcon, Search} from "lucide-react"

import {createTreeCollection} from "@qualcomm-ui/core/tree"
import {TextInput} from "@qualcomm-ui/react/text-input"
import {Tree} from "@qualcomm-ui/react/tree"
import type {TreeCollection} from "@qualcomm-ui/utils/collection"
import {matchSorter} from "@qualcomm-ui/utils/match-sorter"

interface Node {
  id: string
  name: string
  nodes?: Node[]
}

export function TreeFilteringDemo(): ReactElement {
  const [collection, setCollection] =
    useState<TreeCollection<Node>>(initialCollection)
  const [expanded, setExpanded] = useState<string[]>([])
  const [query, setQuery] = useState<string>("")

  const search = (value: string) => {
    setQuery(value)

    if (!value) {
      setCollection(initialCollection)
      return
    }

    const nodes = matchSorter(initialCollection.getDescendantNodes(), value, {
      keys: ["name"],
    })
    const nextCollection = initialCollection.filter((node) =>
      nodes.some((n) => n.id === node.id),
    )
    setCollection(nextCollection)
    setExpanded(nextCollection.getBranchValues())
  }

  return (
    <Tree.Root
      className="w-full max-w-sm"
      collection={initialCollection}
      expandedValue={expanded}
      onExpandedValueChange={({expandedValue}) => setExpanded(expandedValue)}
    >
      <TextInput
        aria-label="Search for files"
        className="mb-1"
        onValueChange={search}
        placeholder="Search for files: 'react'"
        size="sm"
        startIcon={Search}
        value={query}
      />
      {collection.rootNode.nodes?.map((parentNode, index) => {
        return (
          <Tree.Nodes
            key={parentNode.id}
            indexPath={[index]}
            node={parentNode}
            renderBranch={({node}) => (
              <Tree.BranchNode>
                <Tree.NodeIndicator />
                <Tree.BranchTrigger />
                <Tree.NodeIcon icon={FolderIcon} />
                <Tree.NodeText>{node.name}</Tree.NodeText>
              </Tree.BranchNode>
            )}
            renderLeaf={({node}) => (
              <Tree.LeafNode>
                <Tree.NodeIndicator />
                <Tree.NodeIcon icon={FileText} />
                <Tree.NodeText>{node.name}</Tree.NodeText>
              </Tree.LeafNode>
            )}
          />
        )
      })}
    </Tree.Root>
  )
}

const initialCollection = createTreeCollection<Node>({
  nodeChildren: "nodes",
  nodeText: (node) => node.name,
  nodeValue: (node) => node.id,
  rootNode: {
    id: "ROOT",
    name: "",
    nodes: [
      {
        id: "node_modules",
        name: "node_modules",
        nodes: [
          {
            id: "@qui",
            name: "@qui",
            nodes: [
              {id: "node_modules/@qualcomm-ui/core", name: "@qualcomm-ui/core"},
              {
                id: "node_modules/@qualcomm-ui/react",
                name: "@qualcomm-ui/react",
              },
              {
                id: "node_modules/@qualcomm-ui/react-core",
                name: "@qualcomm-ui/react-core",
              },
            ],
          },
          {
            id: "node_modules/@types",
            name: "@types",
            nodes: [
              {id: "node_modules/@types/react", name: "react"},
              {id: "node_modules/@types/react-dom", name: "react-dom"},
            ],
          },
        ],
      },
      {
        id: "src",
        name: "src",
        nodes: [
          {id: "src/app.tsx", name: "app.tsx"},
          {id: "src/index.ts", name: "index.ts"},
        ],
      },
      {id: "prettier.config.js", name: "prettier.config.js"},
      {id: "package.json", name: "package.json"},
      {id: "tsconfig.json", name: "tsconfig.json"},
    ],
  },
})

// packages/docs/angular-docs/src/routes/components+/tree+/demos/tree-filtering-demo.ts
import {Component, signal} from "@angular/core"
import {FormsModule} from "@angular/forms"
import {FileText, FolderIcon, Search} from "lucide-angular"

import {IconDirective} from "@qualcomm-ui/angular/icon"
import {TextInputModule} from "@qualcomm-ui/angular/text-input"
import {TreeModule} from "@qualcomm-ui/angular/tree"
import {provideIcons} from "@qualcomm-ui/angular-core/lucide"
import {createTreeCollection} from "@qualcomm-ui/core/tree"
import type {TreeCollection} from "@qualcomm-ui/utils/collection"
import {matchSorter} from "@qualcomm-ui/utils/match-sorter"

interface FileNode {
  id: string
  name: string
  nodes?: FileNode[]
}

const initialCollection = createTreeCollection<FileNode>({
  nodeChildren: "nodes",
  nodeText: (node) => node.name,
  nodeValue: (node) => node.id,
  rootNode: {
    id: "ROOT",
    name: "",
    nodes: [
      {
        id: "node_modules",
        name: "node_modules",
        nodes: [
          {
            id: "@qui",
            name: "@qui",
            nodes: [
              {
                id: "node_modules/@qualcomm-ui/core",
                name: "@qualcomm-ui/core",
              },
              {
                id: "node_modules/@qualcomm-ui/react",
                name: "@qualcomm-ui/react",
              },
              {
                id: "node_modules/@qualcomm-ui/react-core",
                name: "@qualcomm-ui/react-core",
              },
            ],
          },
          {
            id: "node_modules/@types",
            name: "@types",
            nodes: [
              {id: "node_modules/@types/react", name: "react"},
              {id: "node_modules/@types/react-dom", name: "react-dom"},
            ],
          },
        ],
      },
      {
        id: "src",
        name: "src",
        nodes: [
          {id: "src/app.tsx", name: "app.tsx"},
          {id: "src/index.ts", name: "index.ts"},
        ],
      },
      {id: "prettier.config.js", name: "prettier.config.js"},
      {id: "package.json", name: "package.json"},
      {id: "tsconfig.json", name: "tsconfig.json"},
    ],
  },
})

@Component({
  imports: [TreeModule, IconDirective, TextInputModule, FormsModule],
  providers: [provideIcons({FileText, FolderIcon, Search})],
  selector: "tree-filtering-demo",
  template: `
    <div
      class="w-full max-w-sm"
      q-tree-root
      [collection]="initialCollection"
      [expandedValue]="expanded()"
      (expandedValueChanged)="expanded.set($event.expandedValue)"
    >
      <q-text-input
        aria-label="Search for files"
        class="mb-1"
        placeholder="Search for files: 'react'"
        size="sm"
        startIcon="Search"
        [ngModel]="query()"
        (ngModelChange)="search($event)"
      />
      @for (
        node of collection().rootNode.nodes;
        let i = $index;
        track collection().getNodeValue(node)
      ) {
        <q-tree-nodes [indexPath]="[i]" [node]="node">
          <ng-template
            let-branch
            q-tree-branch-template
            [rootNode]="collection().rootNode"
          >
            <div q-tree-branch-node>
              <div q-tree-node-indicator></div>
              <div q-tree-branch-trigger></div>
              <svg q-tree-node-icon qIcon="FolderIcon"></svg>
              <span q-tree-node-text>{{ branch.node.name }}</span>
            </div>
          </ng-template>

          <ng-template
            let-leaf
            q-tree-leaf-template
            [rootNode]="collection().rootNode"
          >
            <div q-tree-leaf-node>
              <div q-tree-node-indicator></div>
              <svg q-tree-node-icon qIcon="FileText"></svg>
              <span q-tree-node-text>{{ leaf.node.name }}</span>
            </div>
          </ng-template>
        </q-tree-nodes>
      }
    </div>
  `,
})
export class TreeFilteringDemo {
  readonly initialCollection = initialCollection
  readonly collection = signal<TreeCollection<FileNode>>(initialCollection)
  readonly expanded = signal<string[]>([])
  readonly query = signal("")

  search(value: string) {
    this.query.set(value)

    if (!value) {
      this.collection.set(initialCollection)
      return
    }

    const nodes = matchSorter(initialCollection.getDescendantNodes(), value, {
      keys: ["name"],
    })
    const nextCollection = initialCollection.filter((node) =>
      nodes.some((n) => n.id === node.id),
    )
    this.collection.set(nextCollection)
    this.expanded.set(nextCollection.getBranchValues())
  }
}
