// packages/frameworks/react/src/radio/radio-group/radio-group-error-text.tsx
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {ReactElement, ReactNode} from "react"

import {AlertCircle} from "lucide-react"

import {
  InputErrorText,
  type InputErrorTextProps,
} from "@qualcomm-ui/react/input"
import {useRadioGroupErrorText} from "@qualcomm-ui/react-core/radio"
import {mergeProps} from "@qualcomm-ui/utils/merge-props"

import {useQdsRadioContext} from "../qds-radio-context"

export interface RadioGroupErrorTextProps extends InputErrorTextProps {
  /**
   * React {@link https://react.dev/learn/passing-props-to-a-component#passing-jsx-as-children children} prop.
   */
  children?: ReactNode
}

export function RadioGroupErrorText({
  children,
  id,
  ...props
}: RadioGroupErrorTextProps): ReactElement {
  const contextProps = useRadioGroupErrorText({id})
  const qdsContext = useQdsRadioContext()
  const mergedProps = mergeProps(
    contextProps,
    qdsContext.getGroupErrorTextBindings(),
    props,
  )

  return (
    <InputErrorText icon={AlertCircle} {...mergedProps}>
      {children}
    </InputErrorText>
  )
}

// packages/frameworks/angular/src/radio/radio-group/radio-group-error-text.component.ts
// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import {Component, computed, input} from "@angular/core"
import {CircleAlert} from "lucide-angular"

import type {LucideIconOrString} from "@qualcomm-ui/angular-core/lucide"
import {CoreRadioGroupErrorTextDirective} from "@qualcomm-ui/angular-core/radio"

import {useQdsRadioContext} from "../qds-radio-context.service"

@Component({
  selector: "[q-radio-group-error-text]",
  standalone: false,
  template: `
    <svg [qIcon]="icon()!" />
    <ng-content />
  `,
})
export class RadioGroupErrorTextComponent extends CoreRadioGroupErrorTextDirective {
  /**
   * Error indicator icon.
   *
   * @default CircleAlert
   */
  readonly icon = input<LucideIconOrString>(CircleAlert)

  protected readonly qdsRadioContext = useQdsRadioContext()

  constructor() {
    super()
    this.trackBindings.extendWith(
      computed(() => this.qdsRadioContext().getGroupErrorTextBindings()),
    )
  }
}
